### ISSUE TITLE
How to implemention PhotoEditor?

### ISSUE THREAD

**Issue by kkm** [burhanrashid52/PhotoEditor#100]
![Image of Yaktocat](https://capturei.tikatoy.com/r/OrN2sp5INQNB.png)

I have some difficulty understanding, why does not show me anything? What have I missed?

I add gradle
`implementation 'ja.burhanrashid52:photoeditor:0.3.3'`

layout.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:background="@color/black"
tools:context=".MainActivity">

<ja.burhanrashid52.photoeditor.PhotoEditorView
    android:id="@+id/photoEditorView"
    android:layout_width="wrap_content"
    android:layout_height="384dp"
    app:photo_src="@drawable/ic_stat_name" />

</android.support.constraint.ConstraintLayout>
```

MainActivity.java:
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        PhotoEditorView mPhotoEditorView = findViewById(R.id.photoEditorView);
        mPhotoEditorView.getSource().setImageResource(R.drawable.ic_stat_name);

        Typeface mTextRobotoTf = ResourcesCompat.getFont(this, R.font.roboto_medium);
        Typeface mEmojiTypeFace = Typeface.createFromAsset(getAssets(), "fonts/emojione-android.ttf");
        PhotoEditor mPhotoEditor = new PhotoEditor.Builder(this, mPhotoEditorView)
                .setPinchTextScalable(true)
                .setDefaultTextTypeface(mTextRobotoTf)
                .setDefaultEmojiTypeface(mEmojiTypeFace)
                .build();
    }
```

**Comment by kateile** [comment]
Same problem here..

**Comment by burhanrashid52** [comment]
It seems to layout implementation issue. Can you please cross check with your layout with `EditImageActivity`?

**Comment by burhanrashid52** [comment]
Found the problem. You have not `rvConstraintTools` inserted. [This](https://github.com/burhanrashid52/PhotoEditor/blob/1a625ef1ac2218e161dfbe7d51461b6cd54fad37/app/src/main/res/layout/activity_edit_image.xml#L81)

**Comment by kateile** [comment]
I have not figured out how to make it work till now. Lets assume I want similar Layout of the editor like the one with Ned Stark. So how my xml need to look like? Like [this](https://github.com/burhanrashid52/PhotoEditor) or [this](https://github.com/burhanrashid52/PhotoEditor/blob/1a625ef1ac2218e161dfbe7d51461b6cd54fad37/app/src/main/res/layout/activity_edit_image.xml#L81).
Is there any sample app?

**Comment by burhanrashid52** [comment]
The library already has the sample app. Check out `EditImageActivity`.

**Comment by kkm** [comment]
Do I have to do everything XML or just one by one?

**Comment by burhanrashid52** [comment]
one by one means ?

**Comment by kkm** [comment]
https://github.com/burhanrashid52/PhotoEditor/blob/1a625ef1ac2218e161dfbe7d51461b6cd54fad37/app/src/main/res/layout/activity_edit_image.xml#L81
I mean, should I copy this row from  81 - 93 or all XML?

**Comment by burhanrashid52** [comment]
Yes, Its a list of tools which we have defined in the sample app. You can customize as per your need.

**Comment by shivadjango** [comment]
even after copying the xml recylerview could not use the tools
