### ISSUE TITLE
Transparency Support - Please ignore (easy solution)

### ISSUE THREAD

**Issue by Shailevy** [burhanrashid52/PhotoEditor#105]
Hi,
Looks like a great a library.

I'm looking to show transparent regions of the image somehow, today they are rendered as white.

How would you suggest I do that ?

**Comment by Shailevy** [comment]
Sorry.. I found the easy way,  I just added a checkers pattern under the view...

**Comment by burhanrashid52** [comment]
Please share your solution here. So others can benefit.

**Comment by Shailevy** [comment]
Your view supports transparency so I just put another imagview under it ( with a transparent pattern) 
If you think its useful maybe we can bake it into the PhotoEditorView it self
