### ISSUE TITLE
How to avoid saving empty areas

### ISSUE THREAD

**Issue by tpatikirikorala** [burhanrashid52/PhotoEditor#113]
When I save the image it saves empty areas of the view as well. Say I load a square photo, the saved image would have black areas on top and bottom like displayed on phone screen.  I am using code from the sample app, the only difference is I am using fragment activity as opposed to activity. Any idea what's happening here? (Note: sample app saves correctly)

**Comment by Sulfkain** [comment]
There are some options on save method, use them like this:

```
val saveSettings = **SaveSettings.Builder().setTransparencyEnabled(false).build()**
            photoEditor.saveAsFile(pathFile, saveSettings, object : PhotoEditor.OnSaveListener {
                override fun onSuccess(imagePath: String) {
                    //success
                }

                override fun onFailure(exception: Exception) {
                    //failure
                }
            })
```

**Comment by burhanrashid52** [comment]
Refer [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Saving)
