### ISSUE TITLE
#Save image with quality not change

### ISSUE THREAD

**Issue by nguyenngoclinhbkhn** [burhanrashid52/PhotoEditor#116]
I cann't save image with quality not change . Example : I have a bitmap with quality is 3264 * 2448 but after i add sticker and text on bitmap and save it. after save new bitmap'quality is 383*681 , it is not good for me. Someone help me. Please .
Thank you everyone

**Comment by burhanrashid52** [comment]
Duplicate of #10 #11

**Comment by nguyenngoclinhbkhn** [comment]
wherther can you draw sticker on bitmap with coordinate and size of sticker same we display on photoview ? how do i get coordiante and size' sticker ? 
Thank you

**Comment by burhanrashid52** [comment]
Currently, you can't. It's not designed to draw directly on the canvas. We add a child in view group and save that image as a bitmap in the end when `saveImage` is called.
