### ISSUE TITLE
Can i add fonts in you code ?

### ISSUE THREAD

**Issue by xee95** [burhanrashid52/PhotoEditor#12]
i am trying to add different font in code and also color selection in fix so can can you help me in this ?

**Comment by burhanrashid52** [comment]
You can add the text with input text and `colorCode` like this

`mPhotoEditor.addText(inputText, colorCode);`

It will take default fonts provided in the builder,If you want diffrent fonts for diffrent text you can set typeface with each text like this

`mPhotoEditor.addText(mTypeface,inputText, colorCode);`

**Comment by burhanrashid52** [comment]
If this has resolved your issue.Please close the issue
