### ISSUE TITLE
PhotoEditorView not displayed because it is too large to fit into a software layer (or drawing cache), needs 9000000 bytes, only 8294400 available

### ISSUE THREAD

**Issue by wekex35** [burhanrashid52/PhotoEditor#120]
Failed to save Image

**Comment by burhanrashid52** [comment]
What is the size of the image you are loading?

**Comment by wekex35** [comment]
Back image of 500dp x 500dp(1.12) transparent and drawing over it.

**Comment by wekex35** [comment]
But Its working perfectly in emulator but not on real device

**Comment by burhanrashid52** [comment]
Share your device details

**Comment by wekex35** [comment]
Issue solved

**Comment by wekex35** [comment]
I was using this
`   <ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toTopOf="@+id/rvConstraintTools"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:photo_src="@drawable/trans"/>`

instead of this

`<ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/rvConstraintTools"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:photo_src="@drawable/trans" />`

Issues arrived may be because of layout_width and layout_height
