### ISSUE TITLE
How to remove border of text and emoji ?

### ISSUE THREAD

**Issue by CrazyCoderAndroid** [burhanrashid52/PhotoEditor#127]
When I add text or emoji on view it shows with a border. How to remove that border when I clicks on photoEditorView means image and shows border when i click on text or emoji ?

**Comment by Sulfkain** [comment]
You can disable the border with
`photoEditor.clearHelperBox()`

But if user click on item it will show the border again, but it's usefull if user will want to remove the view.

**Comment by CrazyCoderAndroid** [comment]
Thanks
