### ISSUE TITLE
I need to add a not draggable/scalable view ?

### ISSUE THREAD

**Issue by Salman-Hameed** [burhanrashid52/PhotoEditor#132]

**Comment by burhanrashid52** [comment]
The source image or the stickers/emoji?

**Comment by Salman-Hameed** [comment]
I need to add frames that should not be draggable ?

**Comment by burhanrashid52** [comment]
So you meant not pinch to scale or not able to move at all?

**Comment by Salman-Hameed** [comment]
yes for a specific view,

**Comment by Salman-Hameed** [comment]
I want to add photo frames in my application.

**Comment by burhanrashid52** [comment]
Frames are not supported.
