### ISSUE TITLE
Add function to flip image horizontally/vertically

### ISSUE THREAD

**Issue by tulang3587** [burhanrashid52/PhotoEditor#14]
For the stickers, wouldn't an image flip functionality be good?

**Comment by burhanrashid52** [comment]
if you have enabled `setPinchTextScalable(true)` than you can rotate the sticker using pinch i.e rotate using two fingers

**Comment by tulang3587** [comment]
Sorry, I meant flipping as in mirroring the image would be a good addition.

**Comment by burhanrashid52** [comment]
Any general use case for mirroring sticker ?

**Comment by tulang3587** [comment]
I think it's a pretty common function in sticker editing apps. Right now manually adding a mirrored bitmap works, but won't it be better if the functionality is available from the library itself?

Probably by adding a 'flip' button on the frame (like the old Aviary SDK):

![1 cldzuyzmbypyxq8hu8xuzw](https://user-images.githubusercontent.com/24726417/38302730-e709f34e-382d-11e8-944e-7a54a855c473.png)

**Comment by burhanrashid52** [comment]
As of now their is no scope for this feature in the library.Hence as alternate solution you can mirror the bitmap before adding it to `PhotoEditorView`

This code will mirror the bitmap

```
BitmapDrawable flip(BitmapDrawable d)
{
    Matrix m = new Matrix();
    m.preScale(-1, 1);
    Bitmap src = d.getBitmap();
    Bitmap dst = Bitmap.createBitmap(src, 0, 0, src.getWidth(), src.getHeight(), m, false);
    dst.setDensity(DisplayMetrics.DENSITY_DEFAULT);
    return new BitmapDrawable(dst);
}
```
Ref: https://stackoverflow.com/questions/7925278/drawing-mirrored-bitmaps-in-android

**Comment by tulang3587** [comment]
Yeah, I suppose we can use that option instead. I'll close this issue.

Thanks for this library!

**Comment by burhanrashid52** [comment]
Your welcome :)
