### ISSUE TITLE
after building PhotoEditor editing options are not showing

### ISSUE THREAD

**Issue by sandeepkumarmishra354** [burhanrashid52/PhotoEditor#141]

**Comment by burhanrashid52** [comment]
Can you please elaborate on the problem? Its little hard to understand.

**Comment by Sulfkain** [comment]
I think he misunderstood your example app with editing options, with your lib which has only the API to edit.

Could be?

**Comment by sandeepkumarmishra354** [comment]
@Sulfkain yes..
