### ISSUE TITLE
can't saveasbitmap

### ISSUE THREAD

**Issue by rezziqbal** [burhanrashid52/PhotoEditor#153]
can't resolve method PhotoEditor.OnSaveBitmap()

**Comment by burhanrashid52** [comment]
Which version are you using?

**Comment by rezziqbal** [comment]
oh sorry maybe i used the old one. the correct one is new OnSaveBitmap() without PhotoEditor.
Thank you for responding

**Comment by burhanrashid52** [comment]
Please close the issue if its resolved
