### ISSUE TITLE
Sticker size limiter

### ISSUE THREAD

**Issue by paoloPastorini** [burhanrashid52/PhotoEditor#157]
I'm trying to make the sticker smaller but can't find where is the
variable that set the minimum size. Any help?

Thanks for your work!

**Comment by softwrengr** [comment]
I'm also looking for that

**Comment by paoloPastorini** [comment]
The variable is in MultiTouchListener.java just edit the minimumScale value for another lower number. 
`//implementation 'ja.burhanrashid52:photoeditor:0.4.0'`
`implementation project(':photoeditor')`
