### ISSUE TITLE
Help with ads

### ISSUE THREAD

**Issue by code-dot-guy** [burhanrashid52/PhotoEditor#169]
I don't know why but the app doesn't show test ads at all .. i tried everything .. but it doesn't show anything .. i even used a sample app to see if it's a problem in my phone but ads worked fine in the sample app , on the photo editor they don't show at all .. any idea ?

**Comment by burhanrashid52** [comment]
Ads are bind to the package name. So that might be the case it works on a sample app. Anyway, this is not the issue of the library so I am closing this issue.
