### ISSUE TITLE
How can I use Stickers and text edit without bottomSheet Fragment

### ISSUE THREAD

**Issue by Racine2Ju** [burhanrashid52/PhotoEditor#17]
Hi, 

I'm trying to make the app with the stickers already next to the picture, so they don' have to appear throught a fragment.
But I can't figure out how to change the manager so it could work.
Can you help me please?

thx

**Comment by burhanrashid52** [comment]
If you already have the sticker or text then you can directly add sticker using `mPhotoEditor.addImage(bitmap);` and also text using `mPhotoEditor.addText(inputText, colorCode);`

**Comment by Racine2Ju** [comment]
I'm trying, but keep having this message error..
 Attempt to invoke virtual method 'android.widget.ImageView ja.burhanrashid52.photoeditor.PhotoEditorView.getSource()' on a null object reference

**Comment by burhanrashid52** [comment]
if this resolves your issue then please mark issue as close
