### ISSUE TITLE
NullPointerException while saving image in Android 8.0

### ISSUE THREAD

**Issue by nabilahmed739** [burhanrashid52/PhotoEditor#175]
### Description
The NullPointerException shows up only in case of the Moto G6 running Android 8.0.
I have tested the same and works fine in other devices (But I don't have any other Android 8.0 device).
I reproduced the issue in both version: **0.3.3 and 0.4.0**

### Method:
`saveAsFile(@NonNull final String imagePath, @NonNull final OnSaveListener onSaveListener)`

### Device details:
Device: **Moto G6 (XT1925-7)**
Android version: **Android 8.0.0**

### Logs:
> 2019-07-18 16:49:18.654 586-586/? D/SurfaceFlinger: duplicate layer name: changing com.xyz.xyz/com.xyz.xyz.activities.PhotoEditActivity to com..xyz.xyz/com.xyz.xyz.activities.PhotoEditActivity#1

> 2019-07-18 16:49:23.486 23880-23880/com.xyz.xyz E/XyzApp: Failed to save edited image
>     java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
>         at ja.burhanrashid52.photoeditor.BitmapUtil.removeTransparency(BitmapUtil.java:30)
>         at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:652)
>         at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:633)
>         at android.os.AsyncTask$2.call(AsyncTask.java:333)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

**Comment by burhanrashid52** [comment]
Fixed in #326
