### ISSUE TITLE
Save as file and async

### ISSUE THREAD

**Issue by peter19992009** [burhanrashid52/PhotoEditor#180]
when i save as file , it use sync. how can i change .execute() to executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)?
i try to extend and overwrite the method but constructor is private

**Comment by burhanrashid52** [comment]
#97 Is the one I am going to merge it soon. So that It can be customizable.

**Comment by sabriauf** [comment]
I have the same issue and i extended the class to fix it. But there are more methods and variables which are not public to call from extended class. Methods on SaveSettings class, BitmapUtil class BrushDrawingView object and saveFilter method in PhotoEditorView.
