### ISSUE TITLE
Saving user input as rgba bitmap, and allow me to blend it with original image

### ISSUE THREAD

**Issue by b0g8** [burhanrashid52/PhotoEditor#19]
First, I'm happy to see this library. I hope you'll maintain it for long time.
I'd need to apply the same effects for several images. For this situation, it would be great if the library returned an rgba bitmap and let me do the blending afterwards.

**Comment by burhanrashid52** [comment]
Issue resolve v.0.2.0
You can get bitmap using `saveAsBitmap(String, OnSaveListener)`
