### ISSUE TITLE
Error inflating class ja.burhanrashid52.photoeditor.PhotoEditorView

### ISSUE THREAD

**Issue by yusrilmr** [burhanrashid52/PhotoEditor#192]
Somehow, I cannot inflate the UI XML that contains PhotoEditorView.
Here is my code:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/transparent">

        <ja.burhanrashid52.photoeditor.PhotoEditorView
            android:id="@+id/photoEditorView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" >
        </ja.burhanrashid52.photoeditor.PhotoEditorView>

</RelativeLayout>
```

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        try {
            final View view = inflater.inflate(R.layout.app_fragment_edit_picture, container, false);
        }
        catch (Exception e) {
            LogHelper.LogError("TEST");
        }

        return null;
    }
```
I put the `try catch` and `return null` there only for testing. 
When I changed the `ja.burhanrashid52.photoeditor.PhotoEditorView` with `RelativeLayout`, it works fine.
Error:

> Binary XML file line #9: Binary XML file line #9: Error inflating class ja.burhanrashid52.photoeditor.PhotoEditorView

Do you have any clue?

**Comment by yusrilmr** [comment]
This one is fixed. There was a wrong implementation.
https://stackoverflow.com/questions/58305804/error-inflating-class-ja-burhanrashid52-photoeditor-photoeditorview/58309128?noredirect=1#comment102980120_58309128

**Comment by burhanrashid52** [comment]
Great. Thanks for asking on StackOverflow. This will definitely help other devs too. Since it is fixed I am closing this issue.
