### ISSUE TITLE
Error:(252, 5) error: duplicate value for resource 'attr/src' with config ''.

### ISSUE THREAD

**Issue by MahendraRaj** [burhanrashid52/PhotoEditor#2]
- Getting this error when I tried to use this library in my app

<img width="1544" alt="screen shot 2018-02-06 at 9 59 54 pm" src="https://user-images.githubusercontent.com/17117994/35871002-2080a8f6-0b89-11e8-87be-848edb5a0cad.png">

**Comment by burhanrashid52** [comment]
Is there any other library in your app which is using `src` in their `attr` folder ?

**Comment by MahendraRaj** [comment]
Thanks for your quick response :) @burhanrashid52 

 - I went through attr.xml file in this library and I see a reference with the name "src" which is conflicting with the value that is in app-compat library. Is it possible to rename the "src" to some other name so that it won't conflict with predefined names in app-compat library ?

**Comment by MahendraRaj** [comment]
Or is there a way to avoid the above error and use your library?

**Comment by ch4ndu** [comment]
The src attribute defined in this library conflicts with the default attribute android has for ImageView. I think you should rename that to something else.
Great library btw!

**Comment by burhanrashid52** [comment]
Thanks for you input.I have already made the changes for the upcoming version

**Comment by MahendraRaj** [comment]
When can I expect the next version to use in my app? @burhanrashid52

**Comment by burhanrashid52** [comment]
I don't have a ETA for it @MahendraRaj .But you can resolve issue mentioned by @ch4ndu

**Comment by burhanrashid52** [comment]
This issue is resolved in new 0.1.1 version @MahendraRaj
