### ISSUE TITLE
Text Cursor issue

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#20]
After i add text and try to edit it by long click, the cursor on text is positioned to starting instead of this it should be positioned to the end of text. please solve this issue

**Comment by burhanrashid52** [comment]
It's not a library issue.
The `TextEditorDialogFragment` dialog is implemented as a sample to showcase the use of the libraries API
You can change this behaviour by simply setting cursor position to the end of the of the Edittext like this in `TextEditorDialogFragment` dialog

```
mAddTextEditText.setText(getArguments().getString(EXTRA_INPUT_TEXT)); 
mAddTextEditText.setSelection(getArguments().getString(EXTRA_INPUT_TEXT).length()); 
```

**Comment by ervinod** [comment]
Thank you very much..... it worked perfectly

**Comment by burhanrashid52** [comment]
Please close the issue if its resolved
