### ISSUE TITLE
you have to change code

### ISSUE THREAD

**Issue by Tarikmnk** [burhanrashid52/PhotoEditor#204]
hi,
This method (parentView.setDrawingCacheEnabled(true);) was deprecated in API level 28.

I was changed this code.
my code ;
<img width="955" alt="Ekran Resmi 2019-11-25 11 27 50" src="https://user-images.githubusercontent.com/46998249/69524234-a494e380-0f76-11ea-9589-6b8434503dcb.png">

**Comment by burhanrashid52** [comment]
Thanks for the heads up. It would be really helpful if you could create a PR for this fix. I will happy to merge it. 😃

**Comment by burhanrashid52** [comment]
Fixed in v.1.1.1
