### ISSUE TITLE
Flutter Availability

### ISSUE THREAD

**Issue by sumitgohil** [burhanrashid52/PhotoEditor#205]
Hey, Burhan
Thank you so much for this Amazing LIbrary. 

It would be really great if any of such dependency is available for flutter. 
Do you've any plans on this?

**Comment by MichelMelhem** [comment]
I already tried   to implement this lib to a native flutter plugin, but ass soon i do that i get c ompilation error

**Comment by sumitgohil** [comment]
I am wondering if similar, doesn't matter 100%. But some of Features like, resizing text, and few more can be made with flutter. No Native Integration.

**Comment by burhanrashid52** [comment]
Currently, there are no plans to support flutter.
