### ISSUE TITLE
Make Stickers and text click-through when partially transparent (have alpha)

### ISSUE THREAD

**Issue by lucianocheng** [burhanrashid52/PhotoEditor#214]
When a sticker / text has alpha, make them click-through as an option.

Related to this closed PR:

https://github.com/burhanrashid52/PhotoEditor/pull/58

**Comment by lucianocheng** [comment]
Blocked by https://github.com/burhanrashid52/PhotoEditor/issues/219.  Specifically, I need to know if its intended behavior for multiple stickers to be selected.  If it is, it changes how the behavior for click-through should work.

**Comment by lucianocheng** [comment]
Copied from https://github.com/burhanrashid52/PhotoEditor/pull/217

Update: I actually have this working but it's a huge change.

Essentially the editor has to keep track of a "mask" of each image that can be used to quickly calculate intersection. This mask must be updated whenever a user resizes an image.

The recalculation of the masks happens on a threadpool, and the storage happens within each MultiTouchListener. It can also sometimes slow down the editor or take up a good amount of memory to store the masks and update them.

I need to clean up the implementation a bit and figure out how to flag it. Also right now I create a threadpool on PhotoEditor and just pass it into MultiTouchListener, which is fine but not great.

Biggest non-obvious problems with trying to solve this:

- Calculating intersection without a mask will make the editor lock up. Trying to get it to traverse the tree then "search" through the image to see if it intersects a alpha pixel is very slow and users will complain
- Traversing the view stack with the resize is very flaky. You can't trust getWidth() and getHeight() at all since the only thing that resizes is the scaling factor on the outer frame of the sticker. Snapshot is the only way to go that makes sense.
- You need a "radius" around each alpha pixel to account for finger width. Basically if a user is trying to select a thin sticker with alpha all around it, hitting it with your finger exactly is very difficult.

**Comment by lucianocheng** [comment]
@burhanrashid52 you can assign this to me

**Comment by burhanrashid52** [comment]
Can you explain what to you mean by "keep track of a "mask" of each image" ? Also by snapshot do you mean the view object snapshot ?

**Comment by lucianocheng** [comment]
> Can you explain what to you mean by "keep track of a "mask" of each image" ?

Right so, if you have ever dealt with computer graphics, it's not unlike ray tracing with a bounding box hierarchy.

Basically every time a user resizes a sticker (img, text, etc), we take a 2-bit "mask" of the view object. It's not a snapshot because it's only tracking if a pixel is alpha or not. Basically if a pixel is filled in this "mask", it's a valid click intersection point. If it's not, it's an alpha pixel and not clickable.

Also key point: this mask is also adjustable based on a radius parameter. So a PhotoEditor user can say: I have "thin" images as stickers with a lot of alpha, I want a 5 pixel "radius" around them so a user doesn't have to touch exactly a non-alpha pixel to select it. It can be "nearby" a non-alpha pixel.

When we get a touch event, we then "walk" the list of sticker masks, translate the touch event, test each for intersection, and return the sticker selected.  This is O(n) where n = number of stickers, which is relatively fast.

These masks get recalculated whenever a user resizes a sticker.

This image kind of illustrates it but I'll find a better one. This process is hard to describe in words, I really need to take some snapshots and show you. I'll do that once I get to porting this over.

![mqtMG](https://user-images.githubusercontent.com/1024778/117202783-1647a280-ada3-11eb-876f-1c1fb0bf0c13.jpg)


> Also by snapshot do you mean the view object snapshot ?

Yes.

**Comment by lucianocheng** [comment]
Related to https://github.com/burhanrashid52/PhotoEditor/pull/58

**Comment by burhanrashid52** [comment]
It's seems complex. My only concern is... would it be worth it to do it now ? Since I did not see much response from users of this library for this feature.

**Comment by lucianocheng** [comment]
It may not be. It may make more sense just to make the appropriate events
available so I can implement it outside the photoeditor object.

This would be tricky though since I would need the ability to "reject" a
selection event. I'd have to think about it. There are other things that
make sense to work on first.
