### ISSUE TITLE
Image Saving Problem

### ISSUE THREAD

**Issue by mrgulshanyadav** [burhanrashid52/PhotoEditor#216]
photoEditor.saveAsBitmap() is not working all the times. why you are not fixing this?? Everything in your library is working except this Saving. How can other people use this library if image saving is not working??

I'm tired of solving this thing from my side. You should solve this issue As Soon As Possible, this saving problem will cause this library to disappear. Everything else is working. Just fix the image saving problem. The app is crashing when saving the image. It does not happen all the time but 80% of the time it is crashing. There are so many issues created on this topic, but there is no solution from your side, that's why I am creating this issue again. you should take the help of any expert, invite any expert to contribute to your library.

**Comment by burhanrashid52** [comment]
I don't have bandwidth to resolve all the issues. This is an open-source project. I am also looking for a maintainer #314 . You can also contribute to this project.
