### ISSUE TITLE
issue when applyng filter

### ISSUE THREAD

**Issue by romaankhanAndroid** [burhanrashid52/PhotoEditor#221]
When applying filter to portrait image ... it takes black borders automatically to left and right of image and adds those unwanted border in the filtered image. please help

**Comment by romaankhanAndroid** [comment]
![filter](https://user-images.githubusercontent.com/59874186/72779513-26854e00-3c42-11ea-882f-311a8cf3ec98.png)

**Comment by jayansonjay** [comment]
I have the same problem, @romaankhanAndroid have you resolved this?

**Comment by romaankhanAndroid** [comment]
> I have the same problem, @romaankhanAndroid have you resolved this?
Just take that image view to wrap content and set ajustViewBounds to true it will work fine

**Comment by KucherenkoIhor** [comment]
@romaankhanAndroid could you please explain how to fix it?

**Comment by KucherenkoIhor** [comment]
Hey @burhanrashid52 . Do you know how to fix this?

**Comment by vasanihardik** [comment]
any one resolved this issue 
if yes share your ans with us 
thank you!

**Comment by romaankhanAndroid** [comment]
> @romaankhanAndroid could you please explain how to fix it?

Just take that image view to wrap content and set ajustViewBounds to true it will work fine

**Comment by burhanrashid52** [comment]
Please close the issue if it gets resolved

**Comment by vasanihardik** [comment]
which file in changed this two line
already in there but still same issue

still not resolved this issue.

**Comment by vasanihardik** [comment]
this issue not resolved @burhanrashid52

**Comment by skyyyme** [comment]
> Just take that image view to wrap content and set ajustViewBounds to true it will work fine

I have the following code in place and I a still getting black bars around my image. @romaankhanAndroid 

```
public void setFilterEffect(PhotoFilter filterType) {
        LayoutParams layoutParams = parentView.getSource().getLayoutParams();
        layoutParams.width = LayoutParams.WRAP_CONTENT;
        layoutParams.height = LayoutParams.WRAP_CONTENT;
        parentView.getSource().setLayoutParams(layoutParams);
        parentView.getSource().setAdjustViewBounds(true);
        parentView.setFilterEffect(filterType);
    }
```

**Comment by yy1023283126** [comment]
anyone can improve this？

**Comment by NahlaSaadAlDeen** [comment]
any one get solution for this issue?
