### ISSUE TITLE
Fix size of close/delete button

### ISSUE THREAD

**Issue by daupawar** [burhanrashid52/PhotoEditor#225]
![Screenshot_2020-02-02-15-24-53](https://user-images.githubusercontent.com/5126613/73606445-58969880-45d0-11ea-935b-0748d28c4c8b.png)

Whenever we scale image with pinch close/delete button is also scaled. is there any way to fix the size of Close button?

**Comment by burhanrashid52** [comment]
Currently, the close button is attached to the view. So whenever that view scale the close button will also scale. There is not any fix for now.

**Comment by daupawar** [comment]
@burhanrashid52 thank you for reply
