### ISSUE TITLE
Feature Request - Gif Sticker Support

### ISSUE THREAD

**Issue by Vitor238** [burhanrashid52/PhotoEditor#228]
Hi! Can you add gif sticker support (like instagram) to the library?
How can I add this feature to my app?
Thanks in advance!

**Comment by pramodkr123** [comment]
Duplicate of #

**Comment by sambhav2358** [comment]
@Vitor238, then it will become another gif or vidoe. After adding the gif, the file wont remain an image anymore. And since this is only an image editor, u cant add gifs!
