### ISSUE TITLE
Zoom photo and just want the image area  issue .

### ISSUE THREAD

**Issue by andywangzhen** [burhanrashid52/PhotoEditor#23]
Thanks for your share ... how to zoom this image in it , and if i just wang to save image area ,what i can do ?

**Comment by burhanrashid52** [comment]
What do you want to zoom? the source image or the sticker image? Currently saving a specific area of the image is not supported.If you have any solution using cropping specific area of the image then Pull Request are welcome

**Comment by burhanrashid52** [comment]
Source Image
