### ISSUE TITLE
Brush changes not saved

### ISSUE THREAD

**Issue by msroid** [burhanrashid52/PhotoEditor#237]
For the first time whatever I do is ok before I hit the save button.
After I saved the edited image, if I use brush again and hit the save button the previous brush paintings would be saved again!
but other things like emoji and text and etc have no problem.
After saving image it kinda cache the brush paintings and no matter if I use it again or undo some steps as soon as I hit the save button the first time brush paintings would be saved and any brush changes after that  would be ignored.
what can I do with this problem?

**Comment by burhanrashid52** [comment]
Sounds familiar to #57
