### ISSUE TITLE
Text styling?

### ISSUE THREAD

**Issue by lakpriya1s** [burhanrashid52/PhotoEditor#244]
Is there any way to add text Bold, italic, underline & stroke(or shadow)?

**Comment by burhanrashid52** [comment]
Currently it's not. But you can add methods to existing TextStyleBuilder class.
https://www.github.com/burhanrashid52/PhotoEditor/tree/master/photoeditor%2Fsrc%2Fmain%2Fjava%2Fja%2Fburhanrashid52%2Fphotoeditor%2FTextStyleBuilder.java.
PR is always welcome 😊

**Comment by Samuel-Morgan-Tyghe** [comment]
I'm Working on this, Any tips on how to implement .setweight() ?

**Comment by Samuel-Morgan-Tyghe** [comment]
@burhanrashid52 I have added a method that creates shadows, my problem is that I can't run the changes to the TextStyleBuilder.java, it only runs the Gradle .jar, do you know how I can fix this?

**Comment by AdhseOne** [comment]
> ¿Hay alguna forma de agregar texto en negrita, cursiva, subrayado y trazo (o sombra)?

I hope that can help you. :) 

https://github.com/burhanrashid52/PhotoEditor/issues/260#issuecomment-667325968
