### ISSUE TITLE
would it be possible to add manual BG removal

### ISSUE THREAD

**Issue by bojjaradhakrishna** [burhanrashid52/PhotoEditor#253]
ref:
https://github.com/GabrielBB/Android-CutOut
exact view:
https://github.com/GabrielBB/Android-CutOut/blob/master/cutout/src/main/java/com/github/gabrielbb/cutout/DrawView.java

**Comment by basitis** [comment]
@bojjaradhakrishna currently, it is not supported and @burhanrashid52  may know if it will included or not.

**Comment by burhanrashid52** [comment]
This problem can be solved by providing a  BG removal source image to the PhotoEditor. Also, I don't see much interest in this feature. Hence closing it.
