### ISSUE TITLE
Add Frame

### ISSUE THREAD

**Issue by anila791** [burhanrashid52/PhotoEditor#264]
kindlt tell how add frame

**Comment by AdhseOne** [comment]
You can put a drawing with a stroke as a background in PhotoEditorView. If you mean something else, send an image to understand. :'v

**Comment by AdhseOne** [comment]
You can put a drawing with a stroke as a background in PhotoEditorView. If you want to say something else, send an image to understand. :'v

**Comment by AdhseOne** [comment]
> por favor diga cómo agregar marco

You can put a drawing with a stroke as a background in PhotoEditorView. If you want to say something else, send an image to understand. : 'v

**Comment by burhanrashid52** [comment]
Duplicate of #8
