### ISSUE TITLE
I want to Edit text on double click and not on long click listener

### ISSUE THREAD

**Issue by Maheshss1** [burhanrashid52/PhotoEditor#267]

**Comment by burhanrashid52** [comment]
There no API to change this behavior. The way to fix is to change the listener on TextView. You need to import the `:photoeditor` module describes in #270 and do the changes [here](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.java#L161)
