### ISSUE TITLE
Unable to modify rounded_border_tv.xml

### ISSUE THREAD

**Issue by ShivanshAnand** [burhanrashid52/PhotoEditor#270]
I am trying to modify ` rounded_border_tv.xml` so as to have custom border style for the text container ( the thing with border and close button ( image ) to display text on image in edit mode ). I have tried everything but am unable to modify it. It is still showing the original rounder border. Is it hard coded somewhere else too ? 

[ NOTE : I am using your demo app and have also tried modifying `rounder_border_text_view.xml` but to no avail ]

**Comment by a-zasypalov** [comment]
@ShivanshAnand in app/build.gradle comment 

`implementation 'ja.burhanrashid52:photoeditor:1.0.0'`

and uncomment

`implementation project(':photoeditor')`

Sample app just using the version from bintray)

**Comment by burhanrashid52** [comment]
@a-zasypalov approach will work. Closing this issue/
