### ISSUE TITLE
Can we draw shapes (Circle,Rect,Arrow etc ?)

### ISSUE THREAD

**Issue by Suyash171** [burhanrashid52/PhotoEditor#274]

**Comment by ankitivo** [comment]
No, it's not possible at the moment. I am also looking for that feature too.

**Comment by ankitbatra11** [comment]
No, it's not possible at the moment. I am looking out for that feature support.

**Comment by burhanrashid52** [comment]
Duplicate of #72

**Comment by abuzer** [comment]
@ankitbatra11 / @burhanrashid52 Is it still not supported? Any chances to be add this feature in near future if not added.
