### ISSUE TITLE
Unable to Use Brush Feature

### ISSUE THREAD

**Issue by shahzad1** [burhanrashid52/PhotoEditor#275]
Here's the code that i'm trying
`    photoEditorView = findViewById(R.id.photoEditorView);
        photoEditorView.getSource().setBackgroundColor(Color.WHITE);
        photoEditor = new PhotoEditor.Builder(this, photoEditorView)
                .setPinchTextScalable(true)
                .build();
        photoEditor.setBrushDrawingMode(true);`

After using above code, I'm getting this error
`    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
        at ja.burhanrashid52.photoeditor.BrushDrawingView.onSizeChanged(BrushDrawingView.java:168)`

**Comment by burhanrashid52** [comment]
Seems like PhotoEditorView size issue. Please check if you have define 'match'_parent' or any static height/width to PhotoEditorView, if you are not setting an image.

**Comment by shahzad1** [comment]
This is the XML
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>


    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerColors"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <TextView
            android:layout_alignParentLeft="true"
            android:id="@+id/tvClear"
            android:layout_margin="8dp"
            android:textColor="@color/blueClr"
            android:text="Clear"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
        <TextView
            android:layout_alignParentRight="true"
            android:id="@+id/tvSave"
            android:layout_margin="8dp"
            android:textColor="@color/blueClr"
            android:text="Save"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />


    </RelativeLayout>


</LinearLayout>`

**Comment by burhanrashid52** [comment]
You need set image on PhotoEditorView before we use brush.
