### ISSUE TITLE
can not run my app after implementing gradle. 

### ISSUE THREAD

**Issue by yoonah5991** [burhanrashid52/PhotoEditor#278]
Manifest merger failed : Attribute application@label value=(@string/app_name_kor) from AndroidManifest.xml:19:9-45
	is also present at [ja.burhanrashid52:photoeditor:1.0.0] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:13:5-57:19 to override.

I got this error. So I did what it says here. 
But I can not run my app. This time I got below error.

Error running 'app': Default Activity not found

**Comment by burhanrashid52** [comment]
closing due to no acitivty. Reopen if you are still facing this issue.
