### ISSUE TITLE
Brush and eraser seem to require double taps in order to get selected

### ISSUE THREAD

**Issue by b0g8** [burhanrashid52/PhotoEditor#29]
The other tabs, like Text, Sticker and Emoji get selected from single tap. This does not always replicate.  Sometimes seems to work at single taps

**Comment by ervinod** [comment]
its not library problem.... i think you are losing focus of current View

**Comment by burhanrashid52** [comment]
Yes, @ervinod is right it's not the library issue. You can make the create more padding, margin or increase the size of the icon to avoid this issue

**Comment by b0g8** [comment]
Only the demo was used, with no changes.

**Comment by burhanrashid52** [comment]
I understand its a losing focus issue or not tapped properly. I mark closed because it's not a library issue
