### ISSUE TITLE
IllegalArgumentException in Android OS 10

### ISSUE THREAD

**Issue by KiranNemani** [burhanrashid52/PhotoEditor#296]
Hi,
I'm getting crash in android OS 10.  Please check the stack trace below to understand better.

Fatal Exception: java.lang.IllegalArgumentException
width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:1148)
android.graphics.Bitmap.createBitmap (Bitmap.java:1115)
android.graphics.Bitmap.createBitmap (Bitmap.java:1065)
android.graphics.Bitmap.createBitmap (Bitmap.java:1026)
**ja.burhanrashid52.photoeditor.BrushDrawingView.onSizeChanged (BrushDrawingView.java:168)**
android.view.View.sizeChange (View.java:23958)
android.view.View.setFrame (View.java:23891)
android.view.View.layout (View.java:23750)
android.widget.RelativeLayout.onLayout (RelativeLayout.java:1103)
android.view.View.layout (View.java:23753)
android.view.ViewGroup.layout (ViewGroup.java:7277)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
android.widget.FrameLayout.onLayout (FrameLayout.java:270)

**Comment by burhanrashid52** [comment]
Added Android 10/11 storage #326. Closing due to no acitivty
