### ISSUE TITLE
How to check if drawing mode is on?

### ISSUE THREAD

**Issue by royraihen** [burhanrashid52/PhotoEditor#297]
How to check if drawing mode is on?

**Comment by burhanrashid52** [comment]
This might help.
https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.java#L381

**Comment by burhanrashid52** [comment]
Please use discussion for this. Thank you.
