### ISSUE TITLE
How To Implement Crop Image Functionality and How to set Custom Template ??

### ISSUE THREAD

**Issue by Kishan7up** [burhanrashid52/PhotoEditor#298]

**Comment by basitis** [comment]
@Kishan7up  Currently, the crop image functionality is not implemented. Can you tell more about custom Template?

**Comment by basitis** [comment]
@Kishan7up Are you able to solve the issue as per [#299]()? Then please close both issues or let me know if you need more help

**Comment by burhanrashid52** [comment]
closing due to no acitivty
