### ISSUE TITLE
I Impliment Crop Functionality With useing External Library ->    implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'

### ISSUE THREAD

**Issue by Kishan7up** [burhanrashid52/PhotoEditor#299]
You Can Use This Library In Tap Of Upload Image Case :
        implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'
1. Manifest :
   <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"/>

2. Add This Line in  Switch-case :  PICK_REQUEST/ CAMERA_REQUEST:
    CropImage.activity(uri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .start(this);
3.  if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK) {
                Uri resultUri = result.getUri();
                Bitmap bitmap = null;
                try {
                    bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), resultUri);
                    mPhotoEditorView.getSource().setImageBitmap(bitmap);

                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }

**Comment by burhanrashid52** [comment]
Thanks for the issue. I will link this to #79 and will close this one.

**Comment by sahil0289** [comment]
> You Can Use This Library In Tap Of Upload Image Case : implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'
> 
> 1. Manifest :
> 2. Add This Line in  Switch-case :  PICK_REQUEST/ CAMERA_REQUEST:
>    CropImage.activity(uri)
>    .setGuidelines(CropImageView.Guidelines.ON)
>    .start(this);
> 3. if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
>    CropImage.ActivityResult result = CropImage.getActivityResult(data);
>    if (resultCode == RESULT_OK) {
>    Uri resultUri = result.getUri();
>    Bitmap bitmap = null;
>    try {
>    bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), resultUri);
>    mPhotoEditorView.getSource().setImageBitmap(bitmap);
>    ```
>            } catch (IOException e) {
>                e.printStackTrace();
>            }
>        } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
>            Exception error = result.getError();
>        }
>    }
>    ```

How did you crop image after highlighting or writing text??
