### ISSUE TITLE
Drawing is not stored for orientation change

### ISSUE THREAD

**Issue by adn1997** [burhanrashid52/PhotoEditor#302]
I've got an activity including the PhotoEditorView. If I put some drawings or text on the view and change the orientation from my device, e.g. from portrait to landscape, all previous drawings disappear.

It wasn't possible for me to store that drawings from outside the library.

**Comment by burhanrashid52** [comment]
The library does not handle the config changes. You can try putting in a fragment and set setRetainInstance as true.

**Comment by adn1997** [comment]
I tried this and the result you can see in the screenshots. The position and size doesn't fit to the picture anymore.
**Before rotating**
![photo_2021-01-12 10 08 46](https://user-images.githubusercontent.com/47034224/104293613-79dd5580-54be-11eb-8d27-ccd907b9ec1e.jpeg)
**After rotating**
![photo_2021-01-12 10 08 52](https://user-images.githubusercontent.com/47034224/104293637-7fd33680-54be-11eb-925c-020194e28ae1.jpeg)

**Comment by burhanrashid52** [comment]
Interesting. Currently, I don't have the bandwidth to add that feature. All PR are welcome.
Also, can you explain a use case here of rotating the screen while editing?

**Comment by burhanrashid52** [comment]
closing due to no acitivty
