### ISSUE TITLE
TEXT changes position

### ISSUE THREAD

**Issue by dev-mher** [burhanrashid52/PhotoEditor#303]
Hi! thanks for the great lib. It is a good job.
I have found a problem with the TEXT
Steps to reproduce:
1. Add any text
2. Long click and stay press on the text
3. After opening the second screen to modify the text, it is possible to change the source(target) text position on the first screen by moving it(sometimes the keyboard can up the source text too)
Could you please, help me to work around the problem?

**Comment by burhanrashid52** [comment]
Sorry. I did not get it. What do you mean by moving the source text position? Do mean you the text added on PhotoEditorView?
Also, it will be helpful if you can attach a video/gif/image to make it more clear.

**Comment by dev-mher** [comment]
Thanks for the reply!
At first, I add the Text by `PhotoEditor.addText("Any Text", TextStyleBuilder)`
Then, after a long click on the text ("Any Text") it's invoked the callback `onEditTextChangeListener(RootView, AnyText, ColorCode)`
Then, as in the sample app, opens a new window for editing.
And after editing calls ` PhotoEditor.editText(RootView, EditedOrTheSameText, TextStyleBuilder) `
Then my "Any Text" changes his position

**Comment by dev-mher** [comment]
https://user-images.githubusercontent.com/22224513/104819704-48f37c80-5840-11eb-84d4-4ac9b251b6f2.mp4

**Comment by dev-mher** [comment]
https://user-images.githubusercontent.com/22224513/104819762-bd2e2000-5840-11eb-8045-8323d3d59e66.mov

**Comment by dev-mher** [comment]
https://user-images.githubusercontent.com/22224513/104819784-d636d100-5840-11eb-8f43-9f3abfd5e117.mov
