### ISSUE TITLE
how to get image without saving it?

### ISSUE THREAD

**Issue by floweri** [burhanrashid52/PhotoEditor#304]
I want to pass image URL to another activity, but only the image itself without its label and text and other filter effect, how can I get image with it filters?

**Comment by burhanrashid52** [comment]
So you want to pass only filters to the next activity but not the labels and text? If yes, then the library does not handle that. However, you can make it work by just passing the filter type from the intent and set it programmatically in the second activity.

**Comment by burhanrashid52** [comment]
closing due to no acitivty
