### ISSUE TITLE
How can we save edited objects like pen, text, shape and colour in JSON format?

### ISSUE THREAD

**Issue by worldemp-pratikpitale** [burhanrashid52/PhotoEditor#305]
I want save edited part separately, without saving on original image.

**Comment by burhanrashid52** [comment]
Not supported by the library out of the box. Might be related to #119 #26

**Comment by immujahidkhan** [comment]
@worldemp-pratikpitale did you find any solution till now?

**Comment by worldemp-pratikpitale** [comment]
> @worldemp-pratikpitale did you find any solution till now?

Not yet.
