### ISSUE TITLE
Unwanted background color appears

### ISSUE THREAD

**Issue by nvngoc2409** [burhanrashid52/PhotoEditor#309]
Vertical images are of great height will cause the image to add unwanted background color on the sides after applying some filters.
![1612173038337](https://user-images.githubusercontent.com/2100914/106445765-02458980-64b2-11eb-83da-0edc65142ffc.png)

**Comment by burhanrashid52** [comment]
Did you try settings options `setTransparencyEnabled(true)` ?
https://github.com/burhanrashid52/PhotoEditor/wiki/Saving

**Comment by skyyyme** [comment]
I tried `setTransparencyEnabled(true)` doesn't seem to be working. Also, my layout is set up in a way that I can't change width & height of the `PhotoEditorView` these black bars are all around the image when we apply it and is visible in the preview as well after saving with `setTransparencyEnabled(true)`
