### ISSUE TITLE
When the user clicks on Add text, User not able to drag drop text anywhere, It always points to the center. 

### ISSUE THREAD

**Issue by codecracker1993** [burhanrashid52/PhotoEditor#315]
When the user clicks on Add text, User not able to drag drop text anywhere, It always points to the center. 
Can you edit your library with the above function so that users can drag drop text to anywhere in the image. 

Text always points to center of screen. 
It must be drag drop type. As once user clicks on add text, user must be able to drag drop anywhere in the screen.

**Comment by basitis** [comment]
@codecracker1993 The library already providing this functionality. The text will able to drag and drop after you complete editing. Are you referencing some other scenarios?

**Comment by burhanrashid52** [comment]
closing due to no acitivty
