### ISSUE TITLE
emoji, text getting disappeared

### ISSUE THREAD

**Issue by surajpunemaha** [burhanrashid52/PhotoEditor#319]
When I call on `mPhotoEditor.saveAsFile()`. text, emoji's and png added over background getting disappeared.

**Comment by basitis** [comment]
Hi @surajpunemaha 

Are you using as library or as library module? Have you changed anything? Is this things happens in all devices?

**Comment by surajpunemaha** [comment]
`**Are you using as library or as library module?**` Ans = > as library
`**Have you changed anything?**` Ans => No.
`**Is this things happens in all devices?**` Ans=> Yes

**Comment by surajpunemaha** [comment]
> Hi @surajpunemaha
> 
> Are you using as library or as library module? Have you changed anything? Is this things happens in all devices?

Using it as library. (just implementing dependency in gradle). I didn't changed anything. and yes this is happening on all devices.

I am using it in fragment in viewpager.

**Comment by basitis** [comment]
@surajpunemaha  ViewPager with adapter tends to initialize the fragment when you come to that Fragment and your all changes (i.e. emoji, text) will be removed as it is not saved automatically by either the library nor by the Fragment. So one option is, save the image before move to another page (you will not able to edit it though after that)

**Comment by burhanrashid52** [comment]
closing due to no acitivty
