### ISSUE TITLE
Can not write over the stickers, currently it is writing underneath only.

### ISSUE THREAD

**Issue by bhuvinay** [burhanrashid52/PhotoEditor#32]
I am looking to edit pictures same as it is available in WhatsApp, this library is the best match so far.
But one thing that differs is it **cannot write over the stickers**.
![whatsapp image 2018-05-15 at 3 27 08 pm](https://user-images.githubusercontent.com/13121140/40050277-9db16000-5854-11e8-96cf-e50e43d5d685.jpeg)

**Comment by burhanrashid52** [comment]
Yes because 'PhotoEditorView' is `ViewGroup` and `BrushDrawingView` is second child after the source image. Because we are adding sticker,text and emoji as child view on top of each other that's why the last added view will remain on the top and `BrushDrawingView` remains in bottom

**Comment by gagan3035** [comment]
Hi,
I also have the same requirement. It would be great if we have the above functionality in this lib.
Thanks

**Comment by burhanrashid52** [comment]
Noted. I will try to fix this in next release

**Comment by sepehr1014** [comment]
It would be great if this issue was resolved.

**Comment by burhanrashid52** [comment]
I don't have the bandwidth to implement this feature. So closing it for now. If someone wants to fix this and reopen this issue.
