### ISSUE TITLE
Migrating packages to Maven Central

### ISSUE THREAD

**Issue by DenBond7** [burhanrashid52/PhotoEditor#320]
Hello. Due to [JCenter deprecation and end of service](https://developer.android.com/studio/build/jcenter-migration) are you planning to start migrating your packages to a new host, such as [Maven Central](https://maven.apache.org/repository/index.html)?

**Comment by burhanrashid52** [comment]
Yes. But not sure about the timeline. Would you like to contribute for to this migration ?

**Comment by DenBond7** [comment]
@burhanrashid52 unfortunately, I'm new in library publishing. But if I'll have the needed changes I'll create a new pull request. Anyway, we have time up to February 2022

**Comment by burhanrashid52** [comment]
https://search.maven.org/artifact/com.burhanrashid52/photoeditor/1.1.1/aar
