### ISSUE TITLE
How to Set Position of Text, Emoji or Image in View at specific location in PhotoEditorView by PhotoEditor?

### ISSUE THREAD

**Issue by indrapatel8** [burhanrashid52/PhotoEditor#329]
How to Set Position of Text, Emoji or Image in View at specific location in PhotoEditorView by PhotoEditor?

Default is Center-Horizontal-Vertical.

I want to set it to other location....

Kindly provide this feature

**Comment by burhanrashid52** [comment]
Can you please help me understand what is the use case for it?

**Comment by indrapatel8** [comment]
I want to Set Logo in Right Top in default position using addImage(). By Defult it is placed at Center (Horizontal and Vertically).
