### ISSUE TITLE
Problem while getting the Adobe Creative API for release

### ISSUE THREAD

**Issue by Shajeel-Afzal** [burhanrashid52/PhotoEditor#33]
Hi, 

This app is made of the highest quality and I want to customize it and publish on Google Play. 

One problem that I am facing is that I am not able to generate the key for production from the Adobe Creative Cloud. 

It is asking which Creative Component is used in the app. 

Can you please list the procedure for creating the key so that we can publish?

**Comment by burhanrashid52** [comment]
This will help [Publish on google play](https://medium.com/mindorks/upload-your-first-android-app-on-play-store-step-by-step-ee0de9123ac0)

**Comment by burhanrashid52** [comment]
Please close the issue if it is been resolved

**Comment by Shajeel-Afzal** [comment]
@burhanrashid52 the article you mentioned in the comment is just about how to publish the app on Google Play. But I need help in getting the Adobe Creative API for release. Please help in that regard.

**Comment by burhanrashid52** [comment]
Sorry sir, but I don't have much idea about Adobe Creative Cloud publishing. It does seem that it's not a library issue it is more of publishing issue
You can try adobe forum or any other forum to help you out on this issue

**Comment by Shajeel-Afzal** [comment]
Thanks, @burhanrashid52! I'll explore further about the API Key.

**Comment by Shajeel-Afzal** [comment]
Hello @burhanrashid52! Do we need an API key for this to get implemented? Or is it the totally independent library?

**Comment by burhanrashid52** [comment]
Its an independent library
