### ISSUE TITLE
problem dragging sticker

### ISSUE THREAD

**Issue by edoedoardo** [burhanrashid52/PhotoEditor#333]
Hi, thanks for this library!
I noticed a problem with sticker. when I drag it, back to the center as below:

https://user-images.githubusercontent.com/26148419/113726950-f74ae780-96f4-11eb-9d07-1eba087da1b1.mp4

**Comment by burhanrashid52** [comment]
This expected behavior when we try to drag sticker outside the `PhotoEditorView` boundary. Can you check if you are drag outside the PhotoEditorView boundary?

**Comment by edoedoardo** [comment]
I suspected something like this, but the layout is very simple. a match_parent PhotoEditorView on which I just tried adding a sticker.

At the moment I tried the functionality with 2 projects. the first one is a new project (created from zero) and work very well; the second, where i have the problem, is a bit older but use androidX.

some suggestion about the last one?

**Comment by mrvancor** [comment]
> I suspected something like this, but the layout is very simple: a match_parent PhotoEditorView on which I just tried adding a sticker.
> 
> At the moment I tried the functionality on 2 projects. the first one is a new project (created from zero) and work very well; the second, where i have the problem, is a bit older but use androidX.
> 
> any suggestion about the last one?

As temporary solution: add app:photo_src="@android:color/transparent" to PhotoEditorView

**Comment by edoedoardo** [comment]
Hi, thanks for your help. this solution fix the drag problem, but it throw ClassCastException anyway when i try to call the saveAsBitmap method

**Comment by mrvancor** [comment]
> Hi, thanks for your help. this solution fix the drag problem, but it throw ClassCastException anyway when i try to call the saveAsBitmap method without apply filters

As another solution you can use transparent png image or create drawable with transparent color:
`<?xml version="1.0" encoding="utf-8"?>`
`<selector xmlns:android="http://schemas.android.com/apk/res/android">`
`    <item android:drawable="@color/transparent" />`
`</selector>`
and then add app:photo_src="@drawable/transparent"

**Comment by mrvancor** [comment]
I think this issue can be fixed by adding an empty drawable (in else condition) to somewhere in this place: [link](https://github.com/burhanrashid52/PhotoEditor/blob/1f4608b6d891c45b4175504ecbbba211aa08b6c4/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditorView.java#L75).
