### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by Ashvinsolanki7** [burhanrashid52/PhotoEditor#34]
I want to apply some effects on sticker
How to Apply effects on Sticker after view is added how to find which view is currently selected or clicked

**Comment by burhanrashid52** [comment]
Currently, filter effect feature is not available in the library. But you can attach a photo editor listener like this `mPhotoEditor.setOnPhotoEditorListener(this); ` to listen various drawing event while editing view

**Comment by Ashvinsolanki7** [comment]
ohk
