### ISSUE TITLE
Text Not Showing in Sample App

### ISSUE THREAD

**Issue by rahat14** [burhanrashid52/PhotoEditor#343]
Text Not Showing in the sample app 

<a href="https://ibb.co/2Wz6XbK"><img src="https://i.ibb.co/17CnHS2/Screenshot-1619541075.png" alt="Screenshot-1619541075" border="0"></a><br /><br />

**Comment by burhanrashid52** [comment]
Are you able to type and add the text?

**Comment by lucianocheng** [comment]
@rahat14 there's a issue sometimes where you must click on the text field (black screen area) before typing to activate the cursor.
