### ISSUE TITLE
Not able to save image - Snackbar shows Failed to save 

### ISSUE THREAD

**Issue by abdullah230695** [burhanrashid52/PhotoEditor#344]

**Comment by tanoDxyz** [comment]
any additional info :>

**Comment by abdullah230695** [comment]
after selecting the image , when I touch download icon it says "Failed to save image" as a snackBar, the image is not getting saved in gallery.

**Comment by burhanrashid52** [comment]
Can you please share the stack trace of the error.

**Comment by abdullah230695** [comment]
yes see this, Im getting the result in OnFailure method

The log says : **java.io.FileNotFoundException: /storage/emulated/0/Pictures/1620045395282.png.jpg: open failed: EACCES (Permission denied)**

**Comment by burhanrashid52** [comment]
Seems like you did not allow storage permission for the app. Please check and allow the storage permission for the app on setting.

**Comment by abdullah230695** [comment]
actually it doesn't ask for write permission when touching download icon and also its not showing storage option in app settings. so I just removed " maxSdkVersion=28 " from manifest now its showing storage permission in app settings and I just enable it manually now its working . I can able to save image. but the problem is its not asking for write permission at first...

**Comment by abdullah230695** [comment]
To ask permission I just added the permission this code 
**if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.M) {
            if (checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_DENIED) {
                String[] permission = {Manifest.permission.WRITE_EXTERNAL_STORAGE};
                requestPermissions(permission, WRITE_EXTERNAL_STORAGE_CODE);
            }
        }**

**Comment by abdullah230695** [comment]
Anyway you have built a nice project Thankyou so much

**Comment by burhanrashid52** [comment]
@tanoDxyz Do you have any input on this ?

**Comment by tanoDxyz** [comment]
well if @abdullah230695 is running the code on emulator than there is a slight chance that correct code will cause the problem .
second the only thing that came up in my mind while seeing this error is that if `requestLegacyExternalStorage` is used in conjuction with android device that is running android 10 or above - it will cause such error.
