### ISSUE TITLE
I can't add custom text in photoEditor ! please help 

### ISSUE THREAD

**Issue by fsfaysalcse** [burhanrashid52/PhotoEditor#348]
My code is below 

```
       val mPhotoEditor = PhotoEditor.Builder(this, binding.photoEditorView)
            .setPinchTextScalable(true)
            .build()


        var text = TextView(this)
        text.text = "Faysal Ahmed Shakil"
        text.setTextColor(Color.RED)

        val textStyleBuilder = TextStyleBuilder().apply {
            applyStyle(text)
        }


        mPhotoEditor.addText("Hello Faysal",textStyleBuilder)
```

**Comment by burhanrashid52** [comment]
Any error or stacktrace ?

**Comment by fsfaysalcse** [comment]
> Any error or stacktrace ?

Nope ! Text style not applied . Like i set text color as red but still showing black .

**Comment by burhanrashid52** [comment]
I would be hard to track the issue this way. I don't see anything wrong in the code it should work as expected.

**Comment by fsfaysalcse** [comment]
Can you provide me a demo code ?

**Comment by burhanrashid52** [comment]
`EditImageActivity` is the sample code. Check [this](https://github.com/burhanrashid52/PhotoEditor/blob/master/app/src/main/java/com/burhanrashid52/photoediting/EditImageActivity.java#L433).

**Comment by fsfaysalcse** [comment]
I want to add text outline how can i do that  ?

**Comment by iamthreshant** [comment]
I think currently there is no support for text outline. 
Not a perfect solution, but you can try using a different font family which has a default outline.
