### ISSUE TITLE
Save problem with image scaling

### ISSUE THREAD

**Issue by merveAltili** [burhanrashid52/PhotoEditor#35]
In my case, the PhotoEditorView fits the whole screen, so if I save the image, it will be exactly the size of my screen, and the actual image is only a small part of that image.

**Comment by burhanrashid52** [comment]
Same issue as #10

**Comment by merveAltili** [comment]
Is the problem corrected or is it still going on?

**Comment by burhanrashid52** [comment]
It still exists that's why the issue is open

**Comment by merveAltili** [comment]
How much can be fixed?

**Comment by merveAltili** [comment]
How soon can you fix it?

**Comment by burhanrashid52** [comment]
I have marked that issue help wanted. If you have any solution for it than PR's are welcome

**Comment by burhanrashid52** [comment]
Issue partially resolve v.0.2.0
Now while saving the image it will remove unnecessary transparency from the image
