### ISSUE TITLE
Text cross img is not visible

### ISSUE THREAD

**Issue by Android-4** [burhanrashid52/PhotoEditor#353]
after adding text on image box is visible but the cross img which is delete that text is not visible instead of cross img i get grey color dash
![2021-05-24](https://user-images.githubusercontent.com/74585306/119320904-b05f8400-bc99-11eb-9a8c-93c83d217d61.jpg)

**Comment by Android-4** [comment]
Please look into this issue

**Comment by burhanrashid52** [comment]
Does it happened after zooming the image ?

**Comment by Android-4** [comment]
no

**Comment by Android-4** [comment]
even if i dont zoom image i still dont get cross image their

**Comment by Android-4** [comment]
Hello team, any update on this?

**Comment by Android-4** [comment]
Hello team, any update on this?
