### ISSUE TITLE
request for information on the application ban

### ISSUE THREAD

**Issue by syldri** [burhanrashid52/PhotoEditor#359]
hello I would like to know if there is a problem with the application it seems to be prohibited

https://dl.bintray.com/samanjafaridotir/easyCountDownTimerTextview/ja/burhanrashid52/photoeditor/1.1.4/photoeditor-1.1.4.pom

**Comment by burhanrashid52** [comment]
Jcenter was shutdown[ last month](https://developer.android.com/studio/build/jcenter-migration). We have move this library to mavenCenter. You can replace with this new artifiacts
```groovy
implementation 'com.burhanrashid52:photoeditor:{latest-version}
```
For more details please check [this](https://github.com/burhanrashid52/PhotoEditor#getting-started).
