### ISSUE TITLE
Kotlin Migration

### ISSUE THREAD

**Issue by burhanrashid52** [burhanrashid52/PhotoEditor#360]
This issue is created to see demand for Koltin for this library. Please provide your feedback in the comments or you can upvote and downvote the issue.

**Comment by lucianocheng** [comment]
Speaking strictly for myself, this project not being in Kotlin diminishes my ability to contribute.

It is literally my only remaining Android Java project.

**Comment by anderbytes** [comment]
Brace yourselves, I'm working on this. The first commit will be ONLY about converting each JAVA to KOTLIN, right after I'll be working on a commit with the only purpose of replacing the goddamn ASYNC with Coroutines

**Comment by anderbytes** [comment]
All seems to work but I'm having some trouble with the FILE PROVIDER and permissions to save on storage. Don't know why, I can't find the error, I'm missing something and I don't know what it is.

I'll be doing a commit right now, someone please go there and take a look and help me fix it. Thanks!

ps: "photoeditor" library inside the project is working. The permission problem mentioned above is in the photoeditor app of this repository, that implements the library.

**Comment by lucianocheng** [comment]
> All seems to work but I'm having some trouble with the FILE PROVIDER and permissions to save on storage. Don't know why, I can't find the error, I'm missing something and I don't know what it is.

What model / Android version are you running where you see this?

It may be a good idea to not convert the whole project to kotlin at once. Maybe just the `app` first? Or even just the tests would be a huge improvement but a good foray into a larger change.

**Comment by anderbytes** [comment]
I'm doing all my tests on a Moto E5 and a Samsung M31, probably the issue was seen on both, I'd have to look into it again

Everything seems to work... but this. So maybe the full migration to Kotlin is actually possible.

**Comment by anderbytes** [comment]
#418 did a pull request on the app conversion to Kotlin

**Comment by anderbytes** [comment]
> > All seems to work but I'm having some trouble with the FILE PROVIDER and permissions to save on storage. Don't know why, I can't find the error, I'm missing something and I don't know what it is.
> 
> What model / Android version are you running where you see this?
> 
> It may be a good idea to not convert the whole project to kotlin at once. Maybe just the `app` first? Or even just the tests would be a huge improvement but a good foray into a larger change.

Just to point that in the recent Kotlin conversion I had stumbled again with that, but know with more knowledge of Kotlin I was able to solve the issue
