### ISSUE TITLE
not worked onBitmapRead

### ISSUE THREAD

**Issue by alirezazarghi** [burhanrashid52/PhotoEditor#363]
hi can help me, me needed set run time set Filter Effect and save as bitmap   :

 private void setupFilters(Bitmap bitmap) {

        PhotoEditor mPhotoEditor;
        PhotoEditorView mPhotoEditorView;
        Bitmap bitmapFilter;
        mPhotoEditorView = new PhotoEditorView(mContext);
        mPhotoEditor = new PhotoEditor
                .Builder(mContext, mPhotoEditorView)
                .build();
        mPhotoEditorView.getSource().setSaveEnabled(true);
        mPhotoEditorView.getSource().setSaveFromParentEnabled(true);
        String[] sPhotoFilter = getNames(PhotoFilter.class);
        mPhotoEditorView.getSource().setImageBitmap(bitmap);
        for (int i = 0; i < sPhotoFilter.length; i++) {
            mPhotoEditor.clearAllViews();
            mPhotoEditor.addImage(((BitmapDrawable)mPhotoEditorView.getSource().getDrawable()).getBitmap());
            mPhotoEditor.setFilterEffect(PhotoFilter.valueOf(sPhotoFilter[i]));
            mPhotoEditorView.getSource().refreshDrawableState();
            bitmapFilter = ((BitmapDrawable)mPhotoEditorView.getSource().getDrawable()).getBitmap();
            SaveSettings saveSettings = new SaveSettings.Builder()
                    .setClearViewsEnabled(true)
                    .setTransparencyEnabled(true)
                    .build();
            mPhotoEditor.saveAsBitmap(saveSettings,new OnSaveBitmap(){
                @Override
                public void onBitmapReady(Bitmap saveBitmap) {
                    Log.e(TAG, "onBitmapReady: Not work");
                }
                @Override
                public void onFailure(Exception e) {

                }
            });

           mPairList.add(new ImageFilter(sPhotoFilter[i],
                    PhotoFilter.valueOf(sPhotoFilter[i]),
                    bitmapFilter));

        }
    }

not worked onBitmapReady , thx to help me .

**Comment by burhanrashid52** [comment]
I am not sure what you are trying to achieve here ? Can you explain me the usecase ?

**Comment by alirezazarghi** [comment]
help me to create 
![photofilters](https://user-images.githubusercontent.com/46616724/122568008-24255000-cffe-11eb-9cf0-af749fd1f233.gif)
thx
