### ISSUE TITLE
Make the ImageView customisable. 

### ISSUE THREAD

**Issue by gilons** [burhanrashid52/PhotoEditor#364]
**Is your feature request related to a problem? Please describe.**
Currently, I'm working on a react-native library that is using this library in android. I'm interested in using react-native's ImageView implementation as the `resource` but the property `resource` is not assignable(Kotlin).
 
**Describe the solution you'd like**
I think just making the property assignable will give the possibility to the library to use a custom image view other than android's `ImageView`

**Describe alternatives you've considered**

**Additional context**
I can open a PR for that if you wish since I urgently need it.

**Comment by burhanrashid52** [comment]
> ImageView implementation as the resource 

I did not understand it. Can you share an example ?

**Comment by gilons** [comment]
Here https://github.com/burhanrashid52/PhotoEditor/blob/fa11ad85341aa852d946e774bf09da0539d77afd/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditorView.java#L127 
, in the implementation of PhotoEditorView.java, the getResource method returns an ImageView and resource is not assignable .

**Comment by gilons** [comment]
Is that clear enough or you need more details?

**Comment by burhanrashid52** [comment]
You can use `ImageView` instance to set your image.
```java
Resources res = getResources(); /** from an Activity */
photoEditor.getSource().setImageDrawable(res.getDrawable(R.drawable.myimage));
```

**Comment by gilons** [comment]
Is it possible to change the default ImageView?
that's what I want to achieve

**Comment by burhanrashid52** [comment]
No currently it's not.

**Comment by gilons** [comment]
That's the feature I'm currently requesting

**Comment by burhanrashid52** [comment]
What other Object you want in return instead of `ImageView` ?

**Comment by gilons** [comment]
React Natives ImageView implementation

**Comment by burhanrashid52** [comment]
Can you some pseudo code here ?

**Comment by gilons** [comment]
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java

**Comment by gilons** [comment]
> Can you pseudo code here ?

what do you want me to speudocode?
