### ISSUE TITLE
 (BaseActivity.java : 67 )

### ISSUE THREAD

**Issue by syldri** [burhanrashid52/PhotoEditor#367]
hello I have a problem I have this bug that comes up regularly

if you have a solution to that thank you very much

![image](https://user-images.githubusercontent.com/39193219/123445546-4871c580-d5d8-11eb-9a55-f3f955d2658a.png)

![image](https://user-images.githubusercontent.com/39193219/123445173-ec0ea600-d5d7-11eb-958e-85fd8c7d6159.png)

**Comment by burhanrashid52** [comment]
Sorry to say this but this is not how open source project work. You cannot post the crash reporting logs and expects to be fix by us. Please use use issue template by providing more details.
