### ISSUE TITLE
How to unselect All Views on photo editor background click

### ISSUE THREAD

**Issue by ajaydhadhal1111** [burhanrashid52/PhotoEditor#37]

**Comment by burhanrashid52** [comment]
Currently, there is no way to do it. You have to individually tap on the view to unselect it. Will consider this in the future release

**Comment by Sulfkain** [comment]
On a near future I will work on that modification because I need to show icons/images without that border by default.
Maybe a function which shows/hide that border for all and/or one element will be great.

**Comment by burhanrashid52** [comment]
This issue is been fixed on dev branch.
I will release all the bug fixes soon

**Comment by burhanrashid52** [comment]
Resolved v.0.3.1
You can remove helper box using `clearHelperBox()`

**Comment by ajaydhadhal1111** [comment]
Thanks burhanrashid52 for fixing this.
