### ISSUE TITLE
When i zoom in the picture，close button also scaled

### ISSUE THREAD

**Issue by yy1023283126** [burhanrashid52/PhotoEditor#373]
I need to fix it, any suggest can i to improve it？

**Comment by lucianocheng** [comment]
This is related to an issue here: https://github.com/burhanrashid52/PhotoEditor/issues/234.

I linked to a potential solution on that thread. I haven't tried it but there's no reason it shouldn't work.

**Comment by lucianocheng** [comment]
Still looking at this
