### ISSUE TITLE
Android - Media Scanner not working on api 28 (sam sung s8)

### ISSUE THREAD

**Issue by HarryHaiVn** [burhanrashid52/PhotoEditor#378]
Thank you for sharing the project, I tried some functions and got 1 error.
When I store photos on my device (api 28). My collection has been automatically updated. The notifyThatFileIsNowPubliclyAvailable function only calls when > 28 . Looking forward to your response.

**Comment by burhanrashid52** [comment]
Okay seems like not the issue with the library. Do you mean the gallery is not getting updated with a saved image ?
