### ISSUE TITLE
Should disallow drawing on left or right of the image

### ISSUE THREAD

**Issue by stephanepechard** [burhanrashid52/PhotoEditor#379]
**Describe the bug**
Currently, it is possible to draw on the outside (right and left only) of the selected image, due to the way the layout is set.

**To Reproduce**
1. Select an image that lets right and left sides empty (black on the demo app ;
2. Brush on these parts ;
3. You can see shapes on the outside of the image.

**Expected behavior**
It is not possible to draw outside of the given image, drawing should be cropped.

**Screenshot**
![Screenshot_1626709982](https://user-images.githubusercontent.com/703194/126190711-13d6b77f-0d8a-4a41-91ce-442f4d587fda.png)

**Smartphone Info:**
 - Version 1.5.0 on any device

**Comment by burhanrashid52** [comment]
Can we make it configurable from `PhotoEditor.Builder` says setShapeClip(true)` by default it will be false, so that it does not break the existing behavior.

**Comment by ToanNguyen97** [comment]
Hi!, this is a wonderful feature, I really need it but seems it's not have in lastest release version, right?
Please tell me how I can add it, tks

**Comment by burhanrashid52** [comment]
Currently it's not merged and hence not release. Will release it soon.

**Comment by ToanNguyen97** [comment]
tks so much
