### ISSUE TITLE
When I saveFilter，blinking a black sreen

### ISSUE THREAD

**Issue by yy1023283126** [burhanrashid52/PhotoEditor#382]
There is a mask in the demo so it is not obvious

**Comment by burhanrashid52** [comment]
Sorry I did not understand. Can you please use the issue template?

**Comment by anderbytes** [comment]
Just to add a little to the discussion: It never bothered me enough, but when I save the image, for just some milliseconds the editor blinks black, then comes back normally with the content. It's so quick I found it "ok" to handle.

Don't know if that's related to what you said here.

**Comment by yy1023283126** [comment]
> Just to add a little to the discussion: It never bothered me enough, but when I save the image, for just some milliseconds the editor blinks black, then comes back normally with the content. It's so quick I found it "ok" to handle.
> 
> Don't know if that's related to what you said here.

Yes，that‘s it

**Comment by yy1023283126** [comment]
> Just to add a little to the discussion: It never bothered me enough, but when I save the image, for just some milliseconds the editor blinks black, then comes back normally with the content. It's so quick I found it "ok" to handle.
> 
> Don't know if that's related to what you said here.

Do you know how to handle it?

**Comment by anderbytes** [comment]
When I meant Handle I was talking about living with it

**Comment by anderbytes** [comment]
Right now I'm focused on getting #381 done because it's very important here, when my head is clear on that, I'll take a look at your issue.

**Comment by yy1023283126** [comment]
> Right now I'm focused on getting #381 done because it's very important here, when my head is clear on that, I'll take a look at your issue.

Thank you，my friend

**Comment by anderbytes** [comment]
Had some time to look into it... but nothing so far... but it seems something in the internals of the VIEW rendering into the CANVAS, both native from the Java libraries.

Unfortunately the blinking doesn't appear at the correct time if we are debugging, only after we release the debug from pause and the view drawing again.

I would guess we need some expert who knows a lot about GL + graphic rendering on Android.

**Comment by yy1023283126** [comment]
> Had some time to look into it... but nothing so far... but it seems something in the internals of the VIEW rendering into the CANVAS, both native from the Java libraries.
> 
> Unfortunately the blinking doesn't appear at the correct time if we are debugging, only after we release the debug from pause and the view drawing again.
> 
> I would guess we need some expert who knows a lot about GL + graphic rendering on Android.

Yes，that‘s very difficult’

**Comment by anderbytes** [comment]
Don't close it
