### ISSUE TITLE
Get a callback when the image source is touched

### ISSUE THREAD

**Issue by stephanepechard** [burhanrashid52/PhotoEditor#383]
**Feature description**
Depending on the way adding elements (text, stickers, etc.) are added to the view, it may be useful to get a way to know where the user has touched the source image.

**Solution description**
A callback to `OnPhotoEditorListener` should be sufficient. It can be triggered from `imageView.setOnTouchListener` of `
PhotoEditorImpl`.

**Comment by anderbytes** [comment]
Good, would be nice to know how useful this is. Can you tell some examples?

**Comment by stephanepechard** [comment]
My use case is the following: I want my user to add text not with a dedicated button as with the demo app, but on touch on the image when text tool is selected (my UI is quite different). But currently, there's no way to catch any event on the image when Brush mode is off.
