### ISSUE TITLE
Using painting In PhotoEditorView ,  drawing mode is working on "ImageView"  and "RelativeLayout" both  instead of only "ImageView"

### ISSUE THREAD

**Issue by wasim15185** [burhanrashid52/PhotoEditor#385]
**Problems Preview (watch _PaintFragment_)**

**_Updated preview Link_**

![](https://media.giphy.com/media/2saENYjYhCAzwDgvVV/giphy.gif)

**Problems :** 

1. In **PaintFragment**  Although `ja.burhanrashid52.photoeditor.PhotoEditorView` width is `android:layout_width="match_parent"` but it is not stretch width as parent width 
2. We know `PhotoEditorView`  is combination of `ImageView` and `RelativeLayout` , So  `ja.burhanrashid52.photoeditor.PhotoEditorView` width is not as parent then when Draw upon on `ImageView` then it's ok but when draw outside of ImageView means `RelativeLayout` then Drawing is Also working 

_`PhotoEditorView` in **PaintFragment**_

      `<ja.burhanrashid52.photoeditor.PhotoEditorView
            android:id="@+id/paint_view"
            ImgTransitionName="@{@string/img_transition_unique_name}"
            android:layout_width="match_parent"
            android:layout_height="450dp"
            android:layout_marginTop="8dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:photo_src="@drawable/suv" />`

**Comment by burhanrashid52** [comment]
I think #379 might solve this issue. You can also check #380. It there is version `1.5.1`

**Comment by wasim15185** [comment]
Thank You 👍

**Comment by wasim15185** [comment]
@burhanrashid52 but problem with adding Sticker and Text

**Comment by wasim15185** [comment]
@burhanrashid52  but same problem with adding Sticker and Text (Updated)

**Comment by burhanrashid52** [comment]
> @burhanrashid52 but same problem with adding Sticker and Text (Edited Comment)

@stephanepechard Can we fix this ?

**Comment by stephanepechard** [comment]
@wasim15185 I'm not sure to understand the problem. Is it that Stickers and Texts appears outside the source image?

**Comment by wasim15185** [comment]
I am giving the sticker preview and after some time i will give the text preview  because text fragment have some bug and i am redesigning from scratch ...

**preview 1** 
![text ](https://media.giphy.com/media/4eRMkTBwwXP2hSKsLo/giphy.gif)

**preview 2** 
![text ](https://media.giphy.com/media/4eRMkTBwwXP2hSKsLo/giphy.gif)

**Comment by wasim15185** [comment]
@burhanrashid52  please resolve issue
