### ISSUE TITLE
Change the logic of updateView() to be called in onClick()

### ISSUE THREAD

**Issue by jsericksk** [burhanrashid52/PhotoEditor#388]
It seems to me that it makes more sense to call [updateView()](https://github.com/burhanrashid52/PhotoEditor/blob/8d72cf20bc9523f8f10d69a44707316f0d31538d/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/Graphic.java#L89) which triggers onEditTextChangeListener() in onClick() and not onLongClick(), as it is more expected to edit the text right after clicking on it rather than a long click. Are there any special reasons not to do this?

**Comment by burhanrashid52** [comment]
Nothing special. Just a more convenient UX. I am not sure but the click might cause with dragging the text view.

**Comment by jsericksk** [comment]
I can't remember any photo editor app that does this in one long click.

But, in fact, this behavior would not be very ideal for the current structure of the library, as it would make it impossible for the drag and drop event before tapping once to edit, as the text would first need to be selected to get the drag event correctly.

In a more intrusive editing UI, like a dialog, this doesn't really look good, but since I was testing it in an EditText on the editing screen itself, it didn't seem like a bad idea to me.

In this case there should be a better function to identify onClick() events and drag and drop events.

Anyway, thanks for answering.
