### ISSUE TITLE
zoom and rotate imageView

### ISSUE THREAD

**Issue by amirsarafian** [burhanrashid52/PhotoEditor#391]
Is there a way to zoom in and out and rotate image?
if not please add
Thanks

**Comment by burhanrashid52** [comment]
You can use pinch to zoo, rotate and scale.

**Comment by muslimmuda15** [comment]
How to pinch to zoom and rotate?
It just says `Pinch to Scale and Rotate views.` but doesn't show how to do that.

**Comment by muslimmuda15** [comment]
> You can use pinch to zoom, rotate and scale.

How to pinch to zoom and rotate?
It just says `Pinch to Scale and Rotate views`. but doesn't show how to do that.

**Comment by burhanrashid52** [comment]
> > You can use pinch to zoom, rotate and scale.
> 
> How to pinch to zoom and rotate?
> It just says `Pinch to Scale and Rotate views`. but doesn't show how to do that.

https://www.computerhope.com/jargon/p/pinch-to-zoom.htm
