### ISSUE TITLE
Image Breaking Orientation After Filter

### ISSUE THREAD

**Issue by muslimmuda15** [burhanrashid52/PhotoEditor#394]
I want to change the orientation of image after shot from camera from portrait into landscape. So I need to rotation and reduce scale the view like this

```
photoEditor = PhotoEditor
            .Builder(requireContext(), binding.photoEditorView)
            .build()

with(binding.photoEditorView) {
      if (ImageList.images.size > 0) {
          Glide.with(this.source)
              .asBitmap()
              .load(bitmapSource)
              .into(this.source)
      }

      this.rotation = 270F
      this.scaleX = 0.6
      this.scaleY = 0.6
}
```
The result was correct 

![Screenshot_2021-09-16-22-20-34-00](https://user-images.githubusercontent.com/26782958/133641249-2b70e870-674f-4baf-bd79-14e71a539f3d.jpg)

I try to filter the image

```
photoEditor.setFilterEffect(PhotoFilter.AUTO_FIX)
```

I getting the image is breaking like this

![Screenshot_2021-09-16-22-20-48-02](https://user-images.githubusercontent.com/26782958/133641683-4e0ca932-2830-48d1-8d9f-b36b9484004b.jpg)

**Comment by burhanrashid52** [comment]
You are rotating the whole drawing view i.e `PhotoEditorView`. If you want to rotate the image the get `ImageView` from `photoEditorView.getSource()` and applying to rotation to that.
