### ISSUE TITLE
Camera captured Image cropping, filter implementation Issues

### ISSUE THREAD

**Issue by Muzzamildeveloper** [burhanrashid52/PhotoEditor#399]
Sir, I am facing these issues with this library in android 11.
1. when I capture image and click on ok its not opening captured image for cropping.
2. when I am apply filters its showing black screen after saving an image.

**Expected behavior**
1. In first bug camera is capturing image but not showing on activity.
2. In second bug, applying filter showing black screen on save. these issues are only with android 11.

Waiting for your response.

Regards: Muzammil Hussain
Email: mh66966910@gmail.com

**Comment by burhanrashid52** [comment]
A cropping image is not supported. I am not sure how you are cropping it.
