### ISSUE TITLE
is it not possible to add filter effect like instagram provide different shades on images?

### ISSUE THREAD

**Issue by vishalkohad2202** [burhanrashid52/PhotoEditor#4]

**Comment by burhanrashid52** [comment]
No,currently this feature is not implemented.PR's are welcome

**Comment by vishalkohad2202** [comment]
when u will implement this feature as i need it?

**Comment by hololee** [comment]
How about adding shadows to the text?

**Comment by vishalkohad2202** [comment]
The size of photoeditor  view  (Imageview)is fixed? I tried to change it but it does not change

**Comment by burhanrashid52** [comment]
Filter feature is added in v.0.2.0
