### ISSUE TITLE
How to save or resume draft editing ? in which format should I saved?

### ISSUE THREAD

**Issue by immujahidkhan** [burhanrashid52/PhotoEditor#401]
**Describe the bug**
I want to save editing as draft and continue or you can say resume from my draft section?

**To Reproduce**
1. Add image
2. Add text
3. Then how to save draft?
4. If draft can be done then in which format should be I have to saved?
5. If I resume my work from draft then that bitmap should be editable.

**Expected behavior**
I want to allow User to saved draft and resume his work where he left,

**Comment by burhanrashid52** [comment]
Duplicate of #119
