### ISSUE TITLE
How can i add ready made logo/templates?

### ISSUE THREAD

**Issue by immujahidkhan** [burhanrashid52/PhotoEditor#402]
**Describe the bug**
How can I add ready made logo so user can choose and just start renaming? [like this app] (https://play.google.com/store/apps/details?id=org.contentarcade.apps.logomaker) and user can move rotate etc. In short all layers must be moveable

**Comment by burhanrashid52** [comment]
It not supported in this library and currently we don't have any plans for this.

**Comment by immujahidkhan** [comment]
Can you please suggest how it works? i need some road map to make it happen!

**Comment by immujahidkhan** [comment]
@burhanrashid52
