### ISSUE TITLE
Disable Compression

### ISSUE THREAD

**Issue by EbelloImbox** [burhanrashid52/PhotoEditor#411]
Hello I am looking for a way to disable compression, is it possible? 

I am doing compression for my own with other library and I would like to use it because I am doing a double compression right now, with PhotoEditor and later with my own library.

Regards.

**Comment by EbelloImbox** [comment]
I am watching PhotoEditor code and this could be a problem too:

```
private Bitmap captureView(View view) {
        Bitmap bitmap = Bitmap.createBitmap(
                view.getWidth(),
                view.getHeight(),
                Bitmap.Config.ARGB_8888
        );
        Canvas canvas = new Canvas(bitmap);
        view.draw(canvas);
        return bitmap;
    }
```

This is the way to build the final image and it could be a problem because bitmap resolution is the resolution of the view, and view is a PhotoEditorView, so if an user has a low resolution mobile, bitmap will be a low resolution image.

Any help to get a hight quality image from editor?

**Comment by burhanrashid52** [comment]
This library is not designed to handle that. This issue is discussed here #10
