### ISSUE TITLE
Background turns black when put filter

### ISSUE THREAD

**Issue by jdaniel1998** [burhanrashid52/PhotoEditor#416]
![Screenshot_20211122-104418_Both](https://user-images.githubusercontent.com/75588018/142891706-45fdf12a-ff6d-4e31-a8c5-eb37f0e92020.jpg)

**Comment by TheKritix** [comment]
Hi, 

I am experiencing same issue. When I have a picture that is oddly shaped it fills out the edges with a black bar when applying a filter. It is pretty annoying as it is also saved when saving.

Not sure what the solution is, as I haven't been able to sort it.
