### ISSUE TITLE
Shapes opacity doesn't work

### ISSUE THREAD

**Issue by didi789** [burhanrashid52/PhotoEditor#427]
**Describe the bug**
Shapes opacity doesn't work

![image](https://user-images.githubusercontent.com/14198588/147503425-ec7d1a37-6e94-439c-8247-b8c0b06e7fb7.png)

**Comment by burhanrashid52** [comment]
@stephanepechard Can you look into this ?

**Comment by PauliusVal** [comment]
In `DrawingView` paint color must be set before setting the alpha value, so these two lines must be switched:

https://github.com/burhanrashid52/PhotoEditor/blob/e617f96142dae5f5a52fd5d58775ebb99f21a2f9/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/DrawingView.java#L79-L80

**Comment by burhanrashid52** [comment]
@PauliusVal Can raise an PR with test ?
