### ISSUE TITLE
mosaic function

### ISSUE THREAD

**Issue by lisen87** [burhanrashid52/PhotoEditor#429]
Thank you for providing excellent plug-in library. Can you add mosaic function?

**Comment by burhanrashid52** [comment]
Thanks. What do you mean by mosaic function ?

**Comment by lisen87** [comment]
![mmexport1641206763527](https://user-images.githubusercontent.com/20718263/147922168-f5ee165b-ae58-4d15-949c-eb763a05798e.jpg)
like this。
It would be better to have a picture rotation function

**Comment by sambhav2358** [comment]
.

**Comment by sambhav2358** [comment]
.
