### ISSUE TITLE
INSTALLATION IN REACT NATIVE

### ISSUE THREAD

**Issue by Yogesh-Dubey-0804** [burhanrashid52/PhotoEditor#432]
hey im yogesh dubey a newly learned react-native developer @baronha/react-native-photo-editor i was installing this i saw the android installation steps linked to this can anyone please guide me how to install it on react native however i can pay for it but i wanted a real answer.

**Comment by burhanrashid52** [comment]
I don't have much knowledge about react-native. Better to move this issue on [that](https://github.com/baronha/react-native-photo-editor) repo.
