### ISSUE TITLE
Kotlin Doc

### ISSUE THREAD

**Issue by burhanrashid52** [burhanrashid52/PhotoEditor#434]
- [ ] Generate Kotlin doc and publish on Github pages. Similar to Java Doc and push it https://github.com/burhanrashid52/PhotoEditor/tree/gh-pages branch.
- [ ] Update example Java code to Kotlin in README.md and wiki.

**Comment by burhanrashid52** [comment]
@lucianocheng Would you or anyone from your team have the bandwidth to pick this up?

**Comment by lucianocheng** [comment]
@burhanrashid52 assigned myself. Will take a look this week then decide if it makes sense for myself or someone on my team to do it.
