### ISSUE TITLE
New icon / logo

### ISSUE THREAD

**Issue by mansya** [burhanrashid52/PhotoEditor#44]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by burhanrashid52** [comment]
Yeah sure.

**Comment by burhanrashid52** [comment]
Hi, Can you create a logo for this?

**Comment by burhanrashid52** [comment]
Can we have little darker colours @mansya ?

**Comment by mansya** [comment]
So how ? do you like it ?

**Comment by burhanrashid52** [comment]
Hey! Sorry for the late response. Are you still available to create this logo?

**Comment by mansya** [comment]
yes. of course still. do I immediately make pull requests and after that give all the vector files to you?

**Comment by burhanrashid52** [comment]
I like the orange one. Can you create a library banner design?

**Comment by mansya** [comment]
I have create library banner. & I have sent you a [pull request](https://github.com/burhanrashid52/PhotoEditor/pull/136). please check. for all files I have uploaded to [Drive](https://drive.google.com/open?id=1pbv_Mjryd9ODW6c3exNs4ySMd8tcMFb6)

**Comment by burhanrashid52** [comment]
I need a banner image for branding. In your design, it's a PhotoEditor title.

**Comment by mansya** [comment]
did you mean like this ?
![Samsung Mockup](https://user-images.githubusercontent.com/33461607/54440362-20465b80-476d-11e9-89b5-ee385456dee9.png).
if not, you can give me an example.

**Comment by burhanrashid52** [comment]
Yes, Something like that. 
<img width="803" alt="Screenshot 2019-03-17 at 7 44 57 AM" src="https://user-images.githubusercontent.com/14251963/54484261-bde27d80-4888-11e9-8fc2-829d187d895b.png">
You check this example.
1. https://www.uplabs.com/posts/pro-photo-editing-app-ui-sketch-freebie
2. https://www.uplabs.com/posts/music-master

**Comment by mansya** [comment]
Will you not merged this new logo?

**Comment by burhanrashid52** [comment]
Did you check the example above? this is how planning for the design
