### ISSUE TITLE
Camera take picture was very small size

### ISSUE THREAD

**Issue by KeepinRnD** [burhanrashid52/PhotoEditor#456]
When I take picture from camera then took image set and size very small to PhotoEditorView.
![IMAGE 2022-05-13 08:10:44](https://user-images.githubusercontent.com/101090593/168203870-081fd330-5ae3-4cc8-99dc-b39cba150995.jpg)

**Comment by burhanrashid52** [comment]
The issue from not the library. The camera picker is causing the issue.
