### ISSUE TITLE
Image is not saving on some devices

### ISSUE THREAD

**Issue by xee95** [burhanrashid52/PhotoEditor#46]
Image is not saving properly in some devices i test , response is too late for example 20-30minutes after saving image show in folder . can you suggest me why this is happening.

**Comment by burhanrashid52** [comment]
Can you share device details? So I can check from my end

**Comment by xee95** [comment]
Another issue i am facing is while capture image using in-app camera , output is always blurred..

**Comment by KemoHena** [comment]
Same Problem Here, Test on 2 devices, The First On Emulator(BlueStacks), Image Not saved.
Second on my Mobile Galaxy Note 5, Same Problem.

**Comment by KemoHena** [comment]
Hi,
this is not a problem, the saved Images appear after restart Mobile/Emulator

**Comment by xee95** [comment]
@KemoHena  i am talking about real smartphone

**Comment by burhanrashid52** [comment]
Are you guys still facing this issue?

**Comment by burhanrashid52** [comment]
Closing the issue for now. You can reopen it if you have more information about the issue.
