### ISSUE TITLE
ImageFilterView: black background on applying a filter

### ISSUE THREAD

**Issue by uc-sja** [burhanrashid52/PhotoEditor#462]
When I apply filter to any image, the image resizes itself leaving some black background at the borders. Can I have control over that? Can I change the color of that black background?

Also after thoruogh debugging I found out that this happens when mImageFilterView's visibility is set to visible, which means changes need to be done at GLSurfaceView's level. Can you please help me with the same?
![WhatsApp Image 2022-06-27 at 4 59 50 PM](https://user-images.githubusercontent.com/26642483/175938181-8e741550-cac3-4462-b88c-40d204544fe0.jpeg)

**Comment by ubarua123** [comment]
I observed the same behaviour. It resized the image!
