### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by shock-wave007** [burhanrashid52/PhotoEditor#47]
Q1. can i use your code in my project
yes/no

Q2. if (Q1.yes) can u help me how i can use this code in my project
yes/no

Q3. do i need
![capture](https://user-images.githubusercontent.com/29371789/41192843-21f3208e-6c22-11e8-9331-9ada6b541a27.PNG)
add "photoeditor" with "app" to use in my project

**Comment by burhanrashid52** [comment]
A1: Yes you can, its open source
A2: You can get started on the [wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Getting-Started)
A3: It depends if you want to customize the current library then you need to import ':photoeditor' module else you can add via the gradle dependency mention in the wiki

**Comment by shock-wave007** [comment]
In a newly created project 
I added gradel dependcy and sync it
And run following code

mPhotoEditor = new PhotoEditor.Builder(this, mPhotoEditorView)
         .setPinchTextScalable(true)
         .setDefaultTextTypeface(mTextRobotoTf)
         .setDefaultEmojiTypeface(mEmojiTypeFace)
         .build();

Nothing happened.... 
Or I have to use all the file in "app" folder in Q3
