### ISSUE TITLE
Custom font add request

### ISSUE THREAD

**Issue by mehedisoftware** [burhanrashid52/PhotoEditor#470]
Please add custom font function

**Comment by wh173d3v11** [comment]
Hey its already there.. 
as mentioned in thier doc, you can use below snippet.
`mPhotoEditor.addText(mTypeface,inputText, colorCode);`

Here, mTypeface is your CUSTOM FONT and you can able to use bold,italic,underline,strike,shadow also. 

Refer this test case to usage - [TextStyleBuilderTest.kt](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/test/java/ja/burhanrashid52/photoeditor/TextStyleBuilderTest.kt)
