### ISSUE TITLE
PhotoPreview is too small

### ISSUE THREAD

**Issue by Venco-official-275** [burhanrashid52/PhotoEditor#472]
when i use this function
`photoEditor.setClipSourceImage(true)`
the image preview is becomes to small

**Comment by burhanrashid52** [comment]
Can you please share more details.

**Comment by haseebs92** [comment]
photo editor view class has scale type set to CENTER_INSIDE which is making some images too small, this should be changed to fit center

**Comment by aintiqaa-technologies** [comment]
`mPhotoEditorView.source.scaleType = ImageView.ScaleType.CENTER_CROP
`
```
fun loadImage(imgURL: Uri?, errorThumb: Int?, imgView: PhotoEditorView?,mMeasuredWidth:Int) {
imgView?.source?.load(imgURL) {
placeholder(errorThumb ?: 0)
error(errorThumb ?: 0)
memoryCachePolicy(CachePolicy.ENABLED)
allowHardware(false)
size(mMeasuredWidth)
}
}
```

This worked in my case
I am using Coil to load Image
