### ISSUE TITLE
Photo Editor state is lost on configuration change

### ISSUE THREAD

**Issue by mbilal51214** [burhanrashid52/PhotoEditor#473]
**Is your feature request related to a problem? Please describe.**
Problem is when theme is changed like from dark mode to light mode or vice versa. The photoEditorView state is lost, I am using MVVM architecture but there is no way to save the state of photoEditor like there is no way I can save the drawn paths on the view so that I can save in my viewModel and pass to the initializer again after configuration change.

**Describe the solution you'd like**
If in the onPhotoEditorListener I get the drawn paths, and then if there is a mechanism to pass these paths again in the builder, So the states will be maintained, because the lost views will be drawn again.

**Describe alternatives you've considered**
I am thinking to rewrite the whole library, or to search another library that provide this kind of solution.

**Additional context**

**Comment by burhanrashid52** [comment]
Seems like the duplicate of #41 Check my [comment](https://github.com/burhanrashid52/PhotoEditor/issues/41#issuecomment-396121962).
