### ISSUE TITLE
Only image is showed when implementing (V.1.0.5 - JAVA)

### ISSUE THREAD

**Issue by JorgeRedo** [burhanrashid52/PhotoEditor#485]
When I implement all the funcionality, in my PhotoEditorView I only can see the image, so ' can't see the editor menu in the bottom of the app. I have tried to change sizes, but nothing happened.

I have this code:

XML FILE
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".imageProcessor.ImageProcessor">

    <ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>`

Activity
`public class ImageProcessor extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_image_procesor);

        PhotoEditorView mPhotoEditorView = findViewById(com.benasty.benasty.R.id.photoEditorView);

        mPhotoEditorView.getSource().setImageResource(R.drawable.groww);

        //Use custom font using latest support library
        Typeface mTextRobotoTf = ResourcesCompat.getFont(getApplicationContext(), R.font.roboto);

//loading font from asset
        Typeface mEmojiTypeFace = ResourcesCompat.getFont(getApplicationContext(), R.font.roboto);

        PhotoEditor mPhotoEditor = new PhotoEditor.Builder(getApplicationContext(), mPhotoEditorView)
                .setPinchTextScalable(true)
                .setDefaultTextTypeface(mTextRobotoTf)
                .setDefaultEmojiTypeface(mEmojiTypeFace)
                .build();
    }
}`

Any Idea?? I don't know how can I get the menu bar

**Comment by rishujam** [comment]
Hey, Is this project being maintained now?
