### ISSUE TITLE
Transparent image background

### ISSUE THREAD

**Issue by yooneskh** [burhanrashid52/PhotoEditor#49]
How can i have transparent background for image? right now i load the image and save it, but there is some black color around my image. i want it to be only my image and nothing more around it.

**Comment by burhanrashid52** [comment]
Black color in the border or black color in image background?

**Comment by yooneskh** [comment]
the one in the background

**Comment by Sulfkain** [comment]
@yooneskh I have yet achieve this. 
It's really simple, I put my code.:

```
val bitmapEmpty = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
photoEditor.source.setImageBitmap(bitmapEmpty)
```

Then save as usual.
You will get a PNG file with transparent background.

The important, is to get the correct width and height to achieve the same size as your final result.
Keep in mind that on phone / emulator that file shows with white / black background but if you open with another editor image program you will see it's transparent.

I hope this helps you ;)

**Comment by yooneskh** [comment]
hi. thanks for your response. i got it working some time ago. thanks for
your attention

**Comment by burhanrashid52** [comment]
If you have resolved the issue then please post your solution and close the issue. It will really help other developers. @yooneskh

**Comment by Sulfkain** [comment]
@burhanrashid52 Anyway, there is some way to save the transparent layer with the current size, without the `removeTransparency`?
I know that removeTransparency it's for performance but i need the full size
Thank's, great lib!!

**Comment by burhanrashid52** [comment]
Now you can set options while saving the image.
Resolved in v.0.3.2
For more details check Saving [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Saving)
