### ISSUE TITLE
The Opacity doesn't work in the demo

### ISSUE THREAD

**Issue by gabrielnakhata** [burhanrashid52/PhotoEditor#493]
I report a problem in the functionality of setting the opacity of the specific seekBar for this one.

I believe the problem is in the function: Class: ShapeBSFragment in the onProgressChanged function

<img src="https://user-images.githubusercontent.com/5953762/139364880-f7241a02-3f42-43f9-bc56-70fa82f7b493.jpg">

**Comment by burhanrashid52** [comment]
> I report a problem in the functionality of setting the opacity of the specific seekBar for this one.
> 
> I believe the problem is in the function: Class: ShapeBSFragment in the onProgressChanged function
> 
> ![](https://user-images.githubusercontent.com/5953762/139364880-f7241a02-3f42-43f9-bc56-70fa82f7b493.jpg)

do you have a fix for this?

**Comment by gabrielnakhata** [comment]
Good afternoon, I'm actually debugging and I still haven't found a solution, I'm investigating but with some hope that you can help me, I compared the java code that works perfectly to understand at what point it doesn't work, I saw that there is an obsolete function for setOpacity( ), THEN recommend using SetShape()..

![image](https://user-images.githubusercontent.com/86859418/210859814-9ce9cced-9332-4569-958d-3a261a422f30.png)

![image](https://user-images.githubusercontent.com/86859418/210859970-ede453dc-e0cd-44ad-9a95-4816d885563c.png)

**Comment by burhanrashid52** [comment]
@gabrielnakhata Did you try #467 ?

**Comment by gabrielnakhata** [comment]
It worked, but the modification was not merged. It needs to be merged. I made the modification and tried to upload the branch and request a pull request, but I don't have authorization, I can do it if I find it simpler .... @burhanrashid52
