### ISSUE TITLE
Test for opacity functionality

### ISSUE THREAD

**Issue by burhanrashid52** [burhanrashid52/PhotoEditor#496]
[Issue context and description](https://github.com/burhanrashid52/PhotoEditor/pull/495#discussion_r1064059696)

**Comment by burhanrashid52** [comment]
@wasky I am not able to assign this task to you. Can you look into it?

**Comment by wasky** [comment]
I'm waiting for #497 with this to avoid conflicts.

**Comment by wasky** [comment]
After I made changes in dependencies needed for this task I have a following issue:

> The number of method references in a .dex file cannot exceed 64K

There are few possibilities to solve the problem but the simplest is to update `minSdkVersion` to `21` (Android 5.0). I checked that all apps from the README have `minSdkVersion` at least `21`. Also according to stats Android 5.0+ is installed on 98.8% devices. So maybe we could update `minSdkVersion` to `21` in the lib?

**Comment by burhanrashid52** [comment]
> After I made changes in dependencies needed for this task I have a following issue:
> 
> > The number of method references in a .dex file cannot exceed 64K
> 
> There are few possibilities to solve the problem but the simplest is to update `minSdkVersion` to `21` (Android 5.0). I checked that all apps from the README have `minSdkVersion` at least `21`. Also according to stats Android 5.0+ is installed on 98.8% devices. So maybe we could update `minSdkVersion` to `21` in the lib?

I am in for 21.
