### ISSUE TITLE
The character disappears when the image is saved.

### ISSUE THREAD

**Issue by hololee** [burhanrashid52/PhotoEditor#5]
After writing a character in the view, the character disappears when i save the image.

**Comment by burhanrashid52** [comment]
You mean adding special character in text ? Can you elaborate ?

**Comment by hololee** [comment]
i add the text in korean and save the image. after saving image, the text in the view disappeare

**Comment by burhanrashid52** [comment]
I am not able to reproduce the issue.I tried by changing language input to Korean and its works fine

**Comment by hololee** [comment]
Saved image is fine but in photoeditorview the character was disappearing.

**Comment by burhanrashid52** [comment]
You meant you are able to save image with Korean text but not able to see in `PhotoEditorView` , right ?

**Comment by hololee** [comment]
yes :( sorry. i am not good at english..

**Comment by hololee** [comment]
ah  after i save the image(i made customButton, when i clicked this button), the text on the photoeditview is disappeared.

**Comment by burhanrashid52** [comment]
Can you provide  stack-trace/error or a screenshot/video which will be helpful

**Comment by burhanrashid52** [comment]
Not enough information to reproduce the issue....closing this issue for now
