### ISSUE TITLE
How to get removed ViewType in onRemoveViewListener()

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#50]
Hello there,
We can determine which view is added on the paretView in onAddViewListener(ViewType viewType, int numberOfAddedViews) in same way i want to know which view is removed in  onRemoveViewListener().
Please help me to solve this.

**Comment by burhanrashid52** [comment]
Is there any specific use-case to get removed `ViewType`?

**Comment by ervinod** [comment]
Yes.... i want to disable undo and redo functionality when for any specific added functionality, suppose i have added frame (followed some logic like emoji or sticker) and user removed added frame then in this case after pressing undo button frame should not return on undo button pressed....

**Comment by burhanrashid52** [comment]
This issue is been fixed on dev branch.
I will release all the bug fixes soon

**Comment by burhanrashid52** [comment]
Resolved v.0.3.1
