### ISSUE TITLE
Able to draw with brush by zooming or pinching for best results

### ISSUE THREAD

**Issue by shelby-000** [burhanrashid52/PhotoEditor#515]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm not able to zoom or scale while drawing (Brush) by pinching. 

**Describe the solution you'd like**
It will be lot helpful if user can draw brush on image or whatever by pinching.

**Comment by burhanrashid52** [comment]
Currently, I don't have the bandwidth to build this feature. I am happy to merge PR.
