### ISSUE TITLE
Save Image to Cache.

### ISSUE THREAD

**Issue by neman88** [burhanrashid52/PhotoEditor#519]
**Currently Image is saving into the Local?
Hi I don't want to create or save my image on local directory but I want to save it in cache.

**I want to save the Image in Cache for Security Purpose.
Because of the Security purpose I want my image to be Saved in temporary memory of the Application, Please Help me out writing this code.

**Comment by burhanrashid52** [comment]
> **Currently Image is saving into the Local? Hi I don't want to create or save my image on local directory but I want to save it in cache.
> 
> **I want to save the Image in Cache for Security Purpose. Because of the Security purpose I want my image to be Saved in temporary memory of the Application, Please Help me out writing this code.

What you have tried so far?
