### ISSUE TITLE
[Bug] saving an image (even without applying filter or brush or anything) will change image dimensions

### ISSUE THREAD

**Issue by tatsuya25** [burhanrashid52/PhotoEditor#521]
**Describe the bug**
Saving an image (even without applying a filter or brush or anything) will change the image dimensions.

**Expected behavior**
The saved image dimensions should be the same as the original image.

**Comment by tatsuya25** [comment]
Sorry i didn't see it. For anyone wondering i did make a workaround by scaling the image using original image width and height.

Closing this

**Comment by burhanrashid52** [comment]
> Sorry i didn't see it. For anyone wondering i did make a workaround by scaling the image using original image width and height.

Nice!!... I would be really helpful if you can share the solution in the #10 issue.
