### ISSUE TITLE
Make ViewState public, and return back the final Bitmap after saveAsFile

### ISSUE THREAD

**Issue by tamhuynhit** [burhanrashid52/PhotoEditor#525]
Hi @burhanrashid52 
First of all, thank you for your great library, it's really helpful for the community.

1/
My project needs to change the undo button state: if no undo action is available, the button should be disabled. The same for redo button. I see we have `mViewState.addedViewsCount` for all the added views, and `mViewState.redoViewsCount` for all redoable views, but these fields are private.

2/
Can I get the final Bitmap after `suspend fun saveAsFile` method success? `SaveFileResult.Success` have no parameter right now. I can see the `capturedBitmap` variable when you finalize the result file but no way I can get it in the response.

Thanks for your support,
I can provide a PR for these later if you want.

**Comment by burhanrashid52** [comment]
For 1) the undo/redo method returns a boolean where: true => things are there to undo/redo and false => nothing left to undo/redo/

For 2) I don't understand. We have [saveAsBitmap](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.kt#L245) method which returns the bitmap in the callback.

**Comment by tamhuynhit** [comment]
1/ Currently I have to call undo() to know the result, not before it
I need to check if there are any undo/redo actions that can be done before the user click the button.


- When a user draws something on the photo for the first time. I show both undo and redo buttons, and expect undo should be active, redo button should be deactivated.
The only place I can do trigger this is in `onAddViewListener`, the buttons work as expected.

- User adds 3-4 views on the photo, logic still works the same, as expected.
- User hits undo: some view is removed, I check the result of undo() and activate redo button, works as expected.
- User hits undo a second time: works.
- User now hits redo: I can check the result of redo(), this time it returns true (still 1 more left to redo), so I keep it activated. But `onAddViewListener` is also called to add the view back, which deactivates my redo button. Right now it's a bit complicated because I use `onAddViewListener` to detect view changes from the start.

Maybe I use the wrong logic here.

Thank you for your support.

**Comment by wasky** [comment]
Why are you activating redo button in `onAddViewListener()`? I think you can do this only in a place where you call `undo()` (probably in undo button click listener).

**Comment by tamhuynhit** [comment]
Both buttons are set to GONE from the beginning and are only shown when something has been drawn or added. That's why I try to find a listener triggered when something is added, `onAddViewListener` is promising. So in `onAddViewListener` I do this: Show both buttons (VISIBLE), Undo on, Redo off. 

But in the case above, `onAddViewListener` is also called when a view is added again by Redo action, which makes the Redo button off, but it should be on because there are still more redo actions ahead.

**Comment by wasky** [comment]
* Change the initial state of undo button to disabled and not visible
* In `onAddViewListener` change undo button visibility but do not change enabled state
* Enable redo button on undo button click
* Disable redo button on redo click when `photoEditor.redo()` returns `false`
