### ISSUE TITLE
How to scale source image to fit the space

### ISSUE THREAD

**Issue by KhoaChau0594** [burhanrashid52/PhotoEditor#528]
Hello everyone.
I got a problem with scaling while using the library is the PhotoEditorView doesn't scale the image to fill all the screen width.

I am using Glide to load the image:
```
Glide.with(cont)
        .load(media)
        .into(binding.photoEditorView.source)
```
I have a 653x1024 PNG image, but it just renders half of the photo view

This is when previewing the image, and what I want the PhotoEditorView to display :
![Screenshot 2023-05-21 at 22 14 20](https://github.com/burhanrashid52/PhotoEditor/assets/43965503/c0714b2b-543e-41d6-8253-96a54f58f7d6)

This is when editing the image
![Screenshot 2023-05-21 at 22 15 13](https://github.com/burhanrashid52/PhotoEditor/assets/43965503/ea4da475-4c56-484d-be96-ba1844c2363d)

 I've tried to change the scaleType to fitXY of the binding.photoEditorView.source, but it is still the same. If the scaleType is CENTER, the editor just shows the center of the image
![Screenshot 2023-05-21 at 22 23 19](https://github.com/burhanrashid52/PhotoEditor/assets/43965503/68e8a624-24a2-44bf-8e78-7c1d978bb58c)

Thanks for your help.

**Comment by burhanrashid52** [comment]
Can you try to load this same image using glide on normal `ImageView`? Does it work correctly there ?

**Comment by Harshal624** [comment]
> Can you try to load this same image using glide on normal `ImageView`? Does it work correctly there ?

I'm having the same issue. I am not using Glide though, I am loading image using setImageURI(). I tried loading image on normal imageview, it scales up fine.

**Comment by aintiqaa-technologies** [comment]
mPhotoEditorView.source.scaleType = ImageView.ScaleType.CENTER_CROP

fun loadImage(imgURL: Uri?, errorThumb: Int?, imgView: PhotoEditorView?,mMeasuredWidth:Int) {
    imgView?.source?.load(imgURL) {
        placeholder(errorThumb ?: 0)
        error(errorThumb ?: 0)
        memoryCachePolicy(CachePolicy.ENABLED)
        allowHardware(false)
        size(mMeasuredWidth)
    }
}

This worked in my case
I am using Coil to load Image
