### ISSUE TITLE
Android 10 saveAsFile failed to save File cause by open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by haianhsing** [burhanrashid52/PhotoEditor#535]
**Describe the bug**
Android 10 saveAsFile failed to save File cause by open failed: EACCES (Permission denied)

**To Reproduce**
1. click save button
2. toast "Failed to save Image"

**Expected behavior**
Image Saved Successfully

**Screenshots/Video/GIFs**
If applicable, add screenshots/video/gifs to help explain your problem.

**Smartphone Info:**
 - Device: Pixel3 XL, Honor 20
 - OS: 10
 - Version 3.0.1

**Additional context**
It is recommended to save files using uri instead of file path like this :
```
suspend fun saveImageAsFile(context: Context,uri: Uri): SaveFileResult {
        onBeforeSaveImage()
        val capturedBitmap = buildBitmap()

        val result = withContext(Dispatchers.IO) {
            try {
                context.contentResolver.openOutputStream(uri)?.use { outputStream ->
                    capturedBitmap.compress(
                        saveSettings.compressFormat,
                        saveSettings.compressQuality,
                        outputStream
                    )
                    outputStream.flush()
                }

                SaveFileResult.Success
            } catch (e: IOException) {
                SaveFileResult.Failure(e)
            }
        }

        if (result is SaveFileResult.Success) {
            // Clear all views if it's enabled in save settings
            if (saveSettings.isClearViewsEnabled) {
                boxHelper.clearAllViews(drawingView)
            }
        }

        return result
    }
```

**Comment by burhanrashid52** [comment]
@haianhsing Seems like the sample app does NOT have the READ WRITE storage permission.

**Comment by haianhsing** [comment]
@burhanrashid52 Fails despite having read and write permissions.
Finally, I download source code and use uri to save without read and write permissions.

**Comment by tanoDxyz** [comment]
@haianhsing 
i wrote the sample app's file saving code 
basically library (PhotoEditor) understands file paths and FileSaveHelper uses URI 
and write at that path.

it is a good thing if we have file saving code inside library but let @burhanrashid52 decide that.

moreover on topic 
if you have android 10.
please add video etc and also share your manifest. so  i can have better idea that what is wrong going on🙂

**Comment by tanoDxyz** [comment]
@haianhsing 
please checkout the sample app in photoEditor.

it just declares WRITE_EXTERNAL_STAORAGE
upto api 28 

and remove 
requestLegacyExternalStorage
from your manifest 
and your code will work fine.


remember requestLegacyExternalStorage does not work on higher api levels.
so please do not use it.

**Comment by haianhsing** [comment]
@tanoDxyz Just request WRITE_EXTERNAL_STORAGE without adding requestLegacyExternalStorage into androidmanifest can not work at api 29.  
In the end what I did was using uri in above 28 and file in other
