### ISSUE TITLE
Add possibility to disable clearAllViews onSave

### ISSUE THREAD

**Issue by skined90** [burhanrashid52/PhotoEditor#54]
I have a process with a few steps of uploading image. First step is photo edit using this library and the second step is adding name of image. After saving photo all stickers disappear in scenario if I want to go back from screen where I'm adding name of an image. Is there possibility to add some flag should photoEditor should clear views or not on save?

**Comment by burhanrashid52** [comment]
Sorry for the late response. Depending upon the developer responses for this issue, we will look into for future releases.

**Comment by Sulfkain** [comment]
@burhanrashid52 I'm working on a modification to be able to avoid _BitmapUtil.removeTransparency_; and will be easy to add that kind of customization for _clearAllViews_ too.
Will be merged if i put that change?
I will do with with flags as for ex. [View.setSystemUiVisibility](https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int))

**Comment by burhanrashid52** [comment]
Yeah sure. @Sulfkain 
Create PR than will review the changes and if it works then I am happy to merge.

**Comment by Sulfkain** [comment]
Done https://github.com/burhanrashid52/PhotoEditor/pull/71

**Comment by burhanrashid52** [comment]
Resolved in v.0.3.2
For more details check Saving [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Saving)
