### ISSUE TITLE
How to know that undo and redo option is available

### ISSUE THREAD

**Issue by shailesh2208** [burhanrashid52/PhotoEditor#549]
**Is your feature request related to a problem? Please describe.**
I wan to highlight/un highlight undo and redo button, so how can we know that image has undo and redo functionality, so that we can highlight accordingly and how can we know that user has start drawing on it??

**Comment by burhanrashid52** [comment]
The _undo_ and _redo_ function returns a boolean to check if anything is available to undo redo. You can use that to highlight the state
