### ISSUE TITLE
Margin issues

### ISSUE THREAD

**Issue by munirchauhan** [burhanrashid52/PhotoEditor#55]
Hello there,

When I use the full-screen image then it put start and end margin may I know why it's cut. how to set the image to full screen without cutting
![device-2018-06-13-222026](https://user-images.githubusercontent.com/11899593/41365910-4fe4a3f8-6f58-11e8-8db4-df1776ef58e8.png)

**Comment by burhanrashid52** [comment]
Is your image resolution is same as the device screen resolution?

**Comment by munirchauhan** [comment]
@burhanrashid52  yes image resolution is same as the device screen. is there any chances to get full width image with photo editor?

**Comment by burhanrashid52** [comment]
There is no margin issue. Actually, the image is not of same dimension ratio of the available space for `PhotoEditorView` that's why we see some space left from both sides. If you want to cover the full screen with the image then you change scaleType of the `ImageView` from `mPhotoEditorView.getSource()`.To cover full screen you can set `ScaleType.CENTER_CROP`

**Comment by tamimattafi** [comment]
> There is no margin issue. Actually, the image is not of same dimension ratio of the available space for `PhotoEditorView` that's why we see some space left from both sides. If you want to cover the full screen with the image then you change scaleType of the `ImageView` from `mPhotoEditorView.getSource()`.To cover full screen you can set `ScaleType.CENTER_CROP`

I'm not having any effect from `ScaleType.CENTER_CROP`, the image is still centered in the center, even if I add `centerCrop() `to glide builder, it does make some difference, but the height of the source `imageView` isn't match parent and the photo is just clipped as a square.

Used this as well, but didn't help
```kotlin
        binding.photoEditorView.source.apply {
            layoutParams = RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.MATCH_PARENT,
                RelativeLayout.LayoutParams.MATCH_PARENT,
            )

            scaleType = ImageView.ScaleType.CENTER_CROP
        }
```
