### ISSUE TITLE
Add Button-Controlled Image Rotation Feature

### ISSUE THREAD

**Issue by prasad-shiba** [burhanrashid52/PhotoEditor#551]
**Is your feature request related to a problem? Please describe.**
Currently, there's no option to quickly rotate images, which makes adjusting orientation challenging

**Describe the solution you'd like**
I'd like to see a simple button in the editor that lets users rotate their images 90 degrees in any direction—top, left, bottom, right—with just a click

**Describe alternatives you've considered**
While manual dragging to adjust angles could work, a one-click rotation button is much more user-friendly and efficient

**Additional context**
Right now, the app lacks a feature to rotate images directly

**Comment by burhanrashid52** [comment]
This is a good feature to have. Would you like to contribute it ?

**Comment by prasad-shiba** [comment]
Yes, I'd be happy to contribute this feature. Please let me know if there are any specific guidelines I should follow

**Comment by burhanrashid52** [comment]
Just follow [Contribution](https://github.com/burhanrashid52/PhotoEditor/blob/master/CONTRIBUTING.md) guideline and it just more than enough.
