### ISSUE TITLE
Is there a way to save the modifications made to an image, but not the result image itself?

### ISSUE THREAD

**Issue by williankl** [burhanrashid52/PhotoEditor#556]
Here is the idea, I want to be able to edit the photo in one session, close and come back to continue editing the image later.
For example, add some lines with the brush on the first session, close the app, come back and use the eraser some of the lines I added in the first session.
Is there any way I can store the changes I have made to the image and reapply them once the editing session starts again?

**Comment by burhanrashid52** [comment]
I think you are looking for #26
