### ISSUE TITLE
getEmojis() Function Not Working in Photo Editor SDK 3.0.2

### ISSUE THREAD

**Issue by 0xRahad** [burhanrashid52/PhotoEditor#569]
**Describe the bug**
I am experiencing an issue with the getEmojis function in Photo Editor SDK version 3.0.2. The function is not returning the expected results or is failing to execute properly.

**To Reproduce**
1. Integrate Photo Editor SDK version 3.0.2 in the project.
2. Attempt to use the getEmojis function as per the SDK documentation.
3. Observe that the function does not work as expected.

**Expected behavior**
The getEmojis function should return a list of available emojis as described in the documentation.

**Screenshots/Video/GIFs**

![problem_ss](https://github.com/user-attachments/assets/a2bd2b8d-da87-43ee-8095-deaec041cf3d)

**Comment by burhanrashid52** [comment]
The function was removed from the SDK and was moved to the sample app. Please use the latest version and [emojis list from the sample app](https://github.com/burhanrashid52/PhotoEditor/blob/master/app/src/main/java/com/burhanrashid52/photoediting/EmojiBSFragment.kt#L99).
