### ISSUE TITLE
Can't use with Glide

### ISSUE THREAD

**Issue by tsuharesu** [burhanrashid52/PhotoEditor#59]
Glide starts the request by setting `null` into the ImageView. Your code say it accepts null but 
```
Bitmap getBitmap() {
        return ((BitmapDrawable) getDrawable()).getBitmap();
    }
```
throws a NPE if there is a null drawable.

Code used with Glide: `Glide.with(this).load(someBitmap).into(photoEditorView.source)`

**Comment by burhanrashid52** [comment]
Thanks for posting this issue. I have resolved this issue in dev branch by making null check before fetching bitmap.
I will release this bug fixed in an upcoming release.

**Comment by burhanrashid52** [comment]
Resolved v.0.3.1
