### ISSUE TITLE
The size of photoeditor view (Imageview)is fixed? I tried to change it but it does not change

### ISSUE THREAD

**Issue by vishalkohad2202** [burhanrashid52/PhotoEditor#6]

**Comment by burhanrashid52** [comment]
`PhotoEditorView` is subclass of `RelativeLayout` in which `ImageView` is set in `CENTER` with height/width as `wrap_content`. So yes you can change the height of `RelativeLayout` which will effect the size of `ImageView `too

**Comment by vishalkohad2202** [comment]
I am using the dependency so i am unable to change in the class i.e photoeditor view extends relative layout

**Comment by burhanrashid52** [comment]
You can directly change from xml layout like this
```
<ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="100dp"
        android:layout_height="100dp"
        app:src="@drawable/got_s" />
```

**Comment by burhanrashid52** [comment]
Its working as expected.Closing the issue due to inactivity
