### ISSUE TITLE
Unable set url to PhotoEditorView using picasso.

### ISSUE THREAD

**Issue by vikassminq** [burhanrashid52/PhotoEditor#63]
Picasso.get().load(filePath).into((Target) mPhotoEditorView);
failed to load .

**Comment by burhanrashid52** [comment]
Please share the error logs.

**Comment by burhanrashid52** [comment]
`PhotoEditorView` is a ViewGroup, Picasso needs `ImageView` as a Target. You can get the `ImageView` from `PhotoEditorView` like this `mPhotoEditorView.getSource()`

**Comment by burhanrashid52** [comment]
Please close the issue if it's resolved.

**Comment by Rajkiran21** [comment]
same problem ....image is not loading
