### ISSUE TITLE
Imagem não carrega corretamente API 17

### ISSUE THREAD

**Issue by ramonalmeida** [burhanrashid52/PhotoEditor#64]
Olá.

Estou tendo problemas com a API 17 do Android, veja na imagem que quando a imagem é carregada ela não ocupa o lugar correto. A partir da API 19 funciona perfeitamente.

![erro_api_17](https://user-images.githubusercontent.com/41294201/42759702-451f2e8a-88de-11e8-8727-c3a501c791bc.png)

**Comment by burhanrashid52** [comment]
Can share the device details? and have you tried on some other device of API 17?

**Comment by ramonalmeida** [comment]
Eu uso Virtual Devices... testei nos modelos Nexus 5 e Pixel na API 17 e ambos ocorre o problema.
![erro_api_17_2](https://user-images.githubusercontent.com/41294201/42761471-0dc4e4c4-88e4-11e8-95d8-bc78248c16c1.png)

**Comment by burhanrashid52** [comment]
I have faced the same issue using API 17 emulator. I recommend you to test on the real devices for API below 19

**Comment by burhanrashid52** [comment]
Please close the issue if it's resolved.
