### ISSUE TITLE
Alterar estilo da fonte

### ISSUE THREAD

**Issue by ramonalmeida** [burhanrashid52/PhotoEditor#66]
Olá.

Uma dúvida, existe a possibilidade de alterar o tipo de fonte usando o editText? ou só é possível na instancia do objeto? Estou perguntando porque queria colocar um botão na tela para alterar a fonte e a principio não estou conseguindo.

Exemplo:
_mPhotoEditor.editText(rootView, inputText, colorCode, **mEmojiTypeFace** );_

 ao invés de 

Typeface mEmojiTypeFace = Typeface.createFromAsset(getAssets(), "fonts/Amaze.ttf");

        mPhotoEditor = new PhotoEditor.Builder(this, mPhotoEditorView)
                .setPinchTextScalable(true)
                .setDefaultTextTypeface(mEmojiTypeFace)
                .setDefaultEmojiTypeface(mEmojiTypeFace)
                .build();

**Comment by burhanrashid52** [comment]
So you want to change font type when you edit the text right?

**Comment by ramonalmeida** [comment]
Sim.

**Comment by burhanrashid52** [comment]
You can change the font using this API
`public void editText(View view, Typeface textTypeface, String inputText, int colorCode)`
You need to provide a view which you want to edit with other params.Check [Text wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Text)

**Comment by ramonalmeida** [comment]
Entendi. Vou verificar e aviso se deu certo. 
Existe alguma função ou propriedade do texto que de para alterar o seu alinhamento? Tipo alinhar texto a esquerda, centro ou direita? Eu consigo alterar o alinhamento na tela de edição de texto, mas quando retorna pra tela principal o alinhamento não é atribuído.

**Comment by burhanrashid52** [comment]
Currently, the alignment feature is not supported. We will surely add in upcoming features.

**Comment by ramonalmeida** [comment]
Ok, muito obrigado.
