### ISSUE TITLE
how to handle viewlistener for textview , to get its measurement . ?

### ISSUE THREAD

**Issue by vikassminq** [burhanrashid52/PhotoEditor#67]

**Comment by burhanrashid52** [comment]
Can you please elaborate?

**Comment by vikassminq** [comment]
Initial text view we set at centre  , then using  TextPinch / drag textview on imageview , how we will get update size of textview (Angle, Height , width).

**Comment by burhanrashid52** [comment]
There is no way of doing it. Can you explain your use case for it?

**Comment by burhanrashid52** [comment]
If you want to make text clickable than what is the use of height, width and angle?

**Comment by vikassminq** [comment]
So is their any alternate way for this . without using height , width

**Comment by Sulfkain** [comment]
Why you need the height, width and angle?
If you are asking to make the text clikclable, right now it's not possible.

But will be great if we can customize that click event, that what you want @vikassminq ?
