### ISSUE TITLE
How to add shapes?

### ISSUE THREAD

**Issue by yavuzkoca** [burhanrashid52/PhotoEditor#72]
Does it support to add shapes such as rectangles, arrows or triangles etc?

**Comment by burhanrashid52** [comment]
Currently, custom views are not supported.

**Comment by sepehr1014** [comment]
It would be great if it gets custom view support

**Comment by Suyash171** [comment]
@burhanrashid52 Great Library...!! #kudos 
would be thankful if custom views are been added
