### ISSUE TITLE
Filter thumbnail image is not changed after external image is loaded on view

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#75]
when applying effects to image, instead of currently loaded image, the default butterfly thumbnail image is showing for all filter effects...

**Comment by burhanrashid52** [comment]
The thumbnail images are shown just for a demo purpose. Thumbnail filter images are not the part of the library.

**Comment by ervinod** [comment]
So how can i change thumbnail according to image loaded on imageview....

**Comment by burhanrashid52** [comment]
There is no way of doing it.
