### ISSUE TITLE
MutltiTouchListener  - have one bug.

### ISSUE THREAD

**Issue by trycatchx** [burhanrashid52/PhotoEditor#77]
The code is mistaken in the 67 lines of MutltiTouchListener 

`view.animate().translationY(0).translationY(0);`

The right way ：
`view.animate().translationX(0).translationY(0);`

**Comment by zhangchaojiong** [comment]
`view.animate()._translationY(0).translationY(0);`
Here are two .translationY（）
If TEXT is dragged to the left or right, it will not move back to the origin.

**Comment by burhanrashid52** [comment]
I tried that change but it didn't do anything. Can you share me a video/gif for this change effect ?

**Comment by zhangchaojiong** [comment]
this is gif for this change effect 。 [gif](https://i.imgur.com/ubaGy2v.gif)
you can see that .
if i use code1 ,The picture is dragged to the edge of the X axis and can be returned.
 `view.animate().translationX(0).translationY(0); //code 1`
if i use code2 ,The picture is dragged to the edge of the X axis  and cannot be returned.
 `view.animate().translationY(0).translationY(0); //code 2`

PhotoEditor libs  use code2. but the photo  is fill width in demo，you not able to detect this problem.
if you set marginLeft/marginRight into PhotoEditorView. you can got it.
