### ISSUE TITLE
draw brush bug after eraser

### ISSUE THREAD

**Issue by piseysen** [burhanrashid52/PhotoEditor#80]
I draw with brush work well after  I use eraser, can't draw again, why?

**Comment by piseysen** [comment]
I set other colour but it is still can't draw

**Comment by kustraslawomir** [comment]
Same issue, even in Your sample app @burhanrashid52 

Brush -> Eraser -> Brush

**Comment by buttelicorn** [comment]
i copy whole library to sample and change BrushDrawingView.java to this.
it work well after i add mDrawPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.ADD)) 
in private void refreshBrushDrawing()
<img width="474" alt="0" src="https://user-images.githubusercontent.com/42063496/44386310-b5c19a00-a554-11e8-9cd9-0aa87fa417f9.PNG">

**Comment by SamanFekri** [comment]
I set the `mDrawPaint.setXfermode` to SRC_OVER and the problem solved.
`mDrawPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));`
the whole code is:

    private void refreshBrushDrawing() {
        mBrushDrawMode = true;
        mPath = new Path();
        mDrawPaint.setAntiAlias(true);
        mDrawPaint.setDither(true);
        mDrawPaint.setStyle(Paint.Style.STROKE);
        mDrawPaint.setStrokeJoin(Paint.Join.ROUND);
        mDrawPaint.setStrokeCap(Paint.Cap.ROUND);
        mDrawPaint.setStrokeWidth(mBrushSize);
        mDrawPaint.setAlpha(mOpacity);
        mDrawPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
    }

**Comment by burhanrashid52** [comment]
Bug Fixed in 0.3.3.
Thanks @SamanFekri

**Comment by bleckasumcom** [comment]
https://github.com/burhanrashid52/PhotoEditor/issues/80#issuecomment-413849168
