### ISSUE TITLE
How to use with Glide/Picasso

### ISSUE THREAD

**Issue by Cool-fire** [burhanrashid52/PhotoEditor#82]
I cant figure out to use PhotoEditor with Glide/Picasso. Tried to use normally but Picassso showing error.

**Comment by burhanrashid52** [comment]
What is the error ?

**Comment by Cool-fire** [comment]
**sorry sir figured it out .**

actually I studied the documentation but didn't paid much attention to the photoEditor.getSource which returns ImageView. Tried just putting  PhotoEditor into Glide.into() like Glide.with(getApplicationContext()).load(ImageFile).into(**photoEditorView**);
But Should have been like:
Glide.with(getApplicationContext()).load(ImageFile).into(**photoEditorView.getSource()**);

Sorry My Mistake and Thanks for Replying.

**Comment by AkshayDandale** [comment]
Showing an error 
Attempt to invoke virtual method 'Android. Graphics. Bitmap android. graphics. drawable. BitmapDrawable. getBitmap() ' on null object reference
