### ISSUE TITLE
Image set Blur after capture

### ISSUE THREAD

**Issue by nawinkhatiwada** [burhanrashid52/PhotoEditor#84]
After clicking the photo from the camera icon, the image is set to blur on `mPhotoEditorView`. What might be the reason? (FYI: I am running the project on 1+ 3T device.)

**Comment by burhanrashid52** [comment]
Well, that's a sample app issue. Not a library issue.

**Comment by burhanrashid52** [comment]
`mPhotoEditorView.getSource()` will return an `ImageView` and load that view into glide target

**Comment by burhanrashid52** [comment]
Check #82
