### ISSUE TITLE
How to add only select emojis?

### ISSUE THREAD

**Issue by KyleRansford** [burhanrashid52/PhotoEditor#85]
Can I only add a select few emojis instead of adding the whole amount of emojis? For example, if I only wanted to add the "smiley face" emojis and nothing else could I do that? If so how? Since I'm not familiar with this.

**Comment by burhanrashid52** [comment]
Yes, you can absolutely do that.

**Comment by KyleRansford** [comment]
Thank you for your reply, but I'm confused on how to do it exactly. I found the `mPhotoEditor.addEmoji(unicode)` line, but it shows `mPhotoEditor.addEmoji(Emojiunicode)` for me. I changed the `(Emojiunicode)` and nothing happed and just had red lines. Can you show an example?

**Comment by PramUkesh** [comment]
What u have used in emoji Unicode place

**Comment by PramUkesh** [comment]
You have to use Unicode of emoji you want to show Google it and if it solved comment your result and close the issue

**Comment by KyleRansford** [comment]
In the place of the `mPhotoEditor.addEmoji(Emojiunicode)` `(Emojiunicode)` I use for instance the unicode (U+1F600) for the "grinning face". When I run the app, it still shows all of the emoji list. I just want the smiley emojis to be shown.

**Comment by burhanrashid52** [comment]
The list of emoji displayed by `EmojiAdapter`. Please check that
And if that resolves than please close the issue.

**Comment by burhanrashid52** [comment]
Closing because of no response.
