### ISSUE TITLE
Adding effect to the picture

### ISSUE THREAD

**Issue by nfp7037** [burhanrashid52/PhotoEditor#87]
Hi. I'm customizing the code you have written. So far I'm changing contrast and brightness and it's working fine. The problem is with saving the edited image. I'm saving edits on a new bitmap, then I update the photoEditorView `ImageBitmap` as below

>                         mPhotoEditorView.getSource().setImageBitmap(bitmap);

I think the problem is about the way changes are applied, considering I'm not using  `RootView`.
I've tried `mPhotoEditorView.removeAllViews();` and then `setImageBitmap` and still no result. Also, I've tried to `addView` but Idk how to do so for a bitmap.

I'd appreciate any help and thumbs up for the code you have written.
Thanks.

**Comment by burhanrashid52** [comment]
Why you are `mPhotoEditorView.removeAllViews();` doing this ?

**Comment by burhanrashid52** [comment]
Do you want to apply the contrast effect on source image or whole `PhotoEditorView`?

**Comment by nfp7037** [comment]
I'd rather whole `PhotoEditorView` but it's only possible after saving stickers, emojis,... and user won't be able to make any changes to those layers (again correct me if I'm wrong). 
So, I think maybe with applying changes only on the source image, it will work fine.

**Comment by burhanrashid52** [comment]
To apply filter effect on source image check [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Filter-Effect)
