### ISSUE TITLE
Getting edited image as bitmap

### ISSUE THREAD

**Issue by AtomicSpider** [burhanrashid52/PhotoEditor#9]
Hi,
How can I get edited the image as a bitmap instead of saving it into a file?

**Comment by siberianbearr** [comment]
I don't think you can currently do this but it should be fairly easy to extend the library. Look at the save code. https://github.com/burhanrashid52/PhotoEditor/blob/39775727d9ab2eac4d9d520f77e1d0f7cada5e08/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.java#L438

**Comment by burhanrashid52** [comment]
Agree with @siberianbearr

**Comment by burhanrashid52** [comment]
Issue resolve v.0.2.0
You can get bitmap using `saveAsBitmap(String, OnSaveListener)`
