### ISSUE TITLE
Text front chnage

### ISSUE THREAD

**Issue by FarhanSaikh** [burhanrashid52/PhotoEditor#91]
I want to have multiple front to choose , In the current scenario only one front is available. How to do that ?
I read doc but not able to get it. Thanks .

**Comment by burhanrashid52** [comment]
This [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Text) will help.
The sample app does not showcase that how to add fonts in the text. But you can do by using `mPhotoEditor.addText(yourFontTypeface,yourtext,youtextcolorcode)`
You need to create your own font selector and that by the selected font typeface to above code.

**Comment by FarhanSaikh** [comment]
### Can I change the background color of the photoeditorview using ColorPickerAdapter exist in the project?
If you please help in that case. Will be thank full.
(I am trying to change the background color of transparent image by chnaging photoeditorview )

**Comment by FarhanSaikh** [comment]
> 
> 
> This [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Text) will help.
> The sample app does not showcase that how to add fonts in the text. But you can do by using `mPhotoEditor.addText(yourFontTypeface,yourtext,youtextcolorcode)`
> You need to create your own font selector and that by the selected font typeface to above code.

Thank you for your quick reply dear.
