### ISSUE TITLE
MultiTouchListener has a bug with stickers

### ISSUE THREAD

**Issue by potibor** [burhanrashid52/PhotoEditor#93]
when sticker is not in view bounds from left and right side , sticker can be disappear.
 You are not controlling that issue

**Comment by burhanrashid52** [comment]
Can share the video?

**Comment by potibor** [comment]
[device-2018-10-18-180115.webm.zip](https://github.com/burhanrashid52/PhotoEditor/files/2492429/device-2018-10-18-180115.webm.zip)

**Comment by burhanrashid52** [comment]
Duplicate of #51
